### ISSUE TITLE
Create artwork for Flash end-of-life

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1029]
@megan-phet We'd like you to create some artwork that will be used on the website and emails to users about the upcoming [end-of-life of Adobe Flash](https://theblog.adobe.com/adobe-flash-update/).

Some ideas we've tossed around:

1. [A Flash gravestone](https://www.google.com/search?q=adobe+flash+dead&client=safari&hl=en&sxsrf=ALeKk01BNNVAf_nY4zMxtSxJAsrkdHlVrw:1584051333342&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjDjp6I-5XoAhWEGM0KHf6zDPQQ_AUoAXoECBQQAw)
2. [Flash with circle and slash](https://images.techhive.com/images/article/2016/12/noflash-100697137-large.jpg)

Maybe try creating something for both of the above and the web team can decide which direction we like best.

@amanda-phet @arouinfar @kathy-phet add ideas as they come to you!

**Comment by amanda-phet** [comment]
Some "cute gravestone" ideas. Instead of R.I.P. it would be the flash logo. 

![image](https://user-images.githubusercontent.com/7852916/76571852-2bb28c80-647e-11ea-83b2-7b87c440224e.png)

![image](https://user-images.githubusercontent.com/7852916/76571899-408f2000-647e-11ea-8d32-62020c8bce4c.png)

![image](https://user-images.githubusercontent.com/7852916/76571937-56044a00-647e-11ea-8e69-30a54525141b.png)

![image](https://user-images.githubusercontent.com/7852916/76571986-72a08200-647e-11ea-8c18-8e0b8dae4141.png)

Something along the lines of this sketch:
![image](https://user-images.githubusercontent.com/7852916/76572216-17bb5a80-647f-11ea-8512-063520898d05.png)

**Comment by megan-phet** [comment]
How is this?
<img width="526" alt="Screen Shot 2020-03-25 at 4 44 04 PM" src="https://user-images.githubusercontent.com/40698031/77592438-ca47e000-6eb7-11ea-8ae0-098d6e353cb5.png">

**Comment by oliver-phet** [comment]
I wonder if the "f" needs to be red so that it is more recognizable?

**Comment by amanda-phet** [comment]
Can you make the style more similar to the examples? I think I prefer the old "toon" style in this case.

**Comment by megan-phet** [comment]
<img width="795" alt="Screen Shot 2020-03-31 at 12 21 24 PM" src="https://user-images.githubusercontent.com/40698031/78061220-20020980-734a-11ea-868e-87605b94b7fc.png">

**Comment by megan-phet** [comment]
<img width="771" alt="Screen Shot 2020-03-31 at 12 24 46 PM" src="https://user-images.githubusercontent.com/40698031/78061475-88e98180-734a-11ea-9b40-7103ad7f349a.png">

**Comment by amanda-phet** [comment]
This is complete and the email went out.
