### ISSUE TITLE
"Gifts" artwork for Ratio and Proportion

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#1034]
@emily-phet has asked for some "gift" artwork for a new sim that is being actively worked on. See https://github.com/phetsims/ratio-and-proportion/issues/22 for full details and context. 

This issue is for tracking progress and discussing feedback. 

Please create 5 differently shaped and styled gifts similar to the ones in this photo. 
![image](https://user-images.githubusercontent.com/7852916/80037905-c2c52800-84b1-11ea-8d7e-b115f44ad154.png)

I think sketching out a few ideas that you come up with is a good place to start, but Emily mentioned that she liked the shapes of 4, 8, and 9 on this example. Please go ahead and attach sketches in this github thread to iterate on as you make progress. Thanks!

**Comment by arouinfar** [comment]
@clmccutchan you can prioritize this above the sim background artwork needed in #1033 and #1032.

**Comment by clmccutchan** [comment]
@amanda-phet you bet! Do you have maximum/minimum dimensions in mind, such that I shouldn't make a very tall, skinny package? Should I just keep the dimensions similar to those in the examples?

**Comment by emily-phet** [comment]
@clmccutchan Good question! 

I don't have exact dimensions, but this might help. The gifts will likely be in a drop down menu (similar to the solutes in [Molarity](https://phet.colorado.edu/sims/html/molarity/latest/molarity_en.html). Where this is a colored square indicating solute color, there would be a gift box with the words "Mystery 1", "Mystery 2", etc. or "Challenge 1" "Challenge 2", etc. next to it. They'll need to be recognizable and distinct even on small mobile devices. 

@zepumph Can you offer any guidance regarding size for what you need?

**Comment by clmccutchan** [comment]
@emily-phet That gives me an idea of the size. The gifts will be pretty small and shouldn't have a lot of detail, but each gift will need to be distinctive from the others.

**Comment by clmccutchan** [comment]
@amanda-phet @emily-phet I have a first rough draft of 7 possible gifts. I've made these drafts 100x100 px, which may still be too large. I've used much brighter colors than the examples above because they will be so small. Note that most of the packages still need some work. Let me know which styles you like, edits you have for colors, and how you might like the patterns/bows/ribbons rearranged.

![Gift Boxes Draft1 042720](https://user-images.githubusercontent.com/25354670/80396843-83f8ee80-8872-11ea-9035-9cd9a7359218.png)

**Comment by amanda-phet** [comment]
These are super cute! I'll leave this to @emily-phet and @zepumph to specify size and feedback.

**Comment by zepumph** [comment]
Over to @emily-phet as the lead designer.

**Comment by emily-phet** [comment]
@clmccutchan Agreed, very cute! After discussing with @zepumph yesterday, and considering the small space available for each, it might be best to go with very simple shapes, and no bow. Maybe "mystery box" is really more what we'll be able to make recognizable, rather than gift. Could you make a couple options similar to the bottom middle box? Could be different shapes, but all having essentially the same dimensions.

**Comment by clmccutchan** [comment]
@emily-phet @amanda-phet Here's a next draft of the boxes. I've simplified all of them and have tried to make them similar in size.

![Box Draft 2 043020](https://user-images.githubusercontent.com/25354670/80760695-8d928880-8af6-11ea-969e-0ec969cc9d2e.png)

**Comment by emily-phet** [comment]
@zepumph Can you use the purple, blue, and red boxes in the sim?

**Comment by emily-phet** [comment]
@clmccutchan These look great. We'll see how they look in the sim, and go from there!

**Comment by clmccutchan** [comment]
@emily-phet Would you like me to give you pngs with transparent backgrounds?

**Comment by emily-phet** [comment]
@clmccutchan that would be great!

**Comment by clmccutchan** [comment]
@emily-phet Here are the .pngs. I've provided a set that is at screen resolution and a set at high resolution so that you can choose what works best. 

The Illustrator file is here: https://drive.google.com/open?id=1ApeJSmDL4_wmSWLI2ZT-VN6g7IijemB8

![MysteryBoxes_HighRes_051520_Box 1](https://user-images.githubusercontent.com/25354670/82084369-716f1980-96a8-11ea-8b09-dcb1df61f03f.png)
![MysteryBoxes_HighRes_051520_Box 2](https://user-images.githubusercontent.com/25354670/82084373-7207b000-96a8-11ea-9499-41f97fae35e8.png)
![MysteryBoxes_HighRes_051520_Box 3](https://user-images.githubusercontent.com/25354670/82084374-72a04680-96a8-11ea-95a1-23a8f65b02fc.png)
![MysteryBoxes_HighRes_051520_Box 4](https://user-images.githubusercontent.com/25354670/82084375-72a04680-96a8-11ea-802c-d56b9c55185d.png)
![MysteryBoxes_HighRes_051520_Box 5](https://user-images.githubusercontent.com/25354670/82084376-7338dd00-96a8-11ea-9cc0-14a8b7a753fe.png)
![MysteryBoxes_HighRes_051520_Box 6](https://user-images.githubusercontent.com/25354670/82084377-7338dd00-96a8-11ea-85f7-b51ad05ff2a2.png)
![MysteryBoxes_ScreenRes_051520_Box 1](https://user-images.githubusercontent.com/25354670/82084378-73d17380-96a8-11ea-92f3-fad5a2754c96.png)
![MysteryBoxes_ScreenRes_051520_Box 2](https://user-images.githubusercontent.com/25354670/82084379-73d17380-96a8-11ea-89de-c76308a80444.png)
![MysteryBoxes_ScreenRes_051520_Box 3](https://user-images.githubusercontent.com/25354670/82084380-73d17380-96a8-11ea-880b-148703bdad7e.png)
![MysteryBoxes_ScreenRes_051520_Box 4](https://user-images.githubusercontent.com/25354670/82084381-746a0a00-96a8-11ea-93fb-f6fc4a4c3ca4.png)
![MysteryBoxes_ScreenRes_051520_Box 5](https://user-images.githubusercontent.com/25354670/82084382-746a0a00-96a8-11ea-8428-c8035e86d506.png)
![MysteryBoxes_ScreenRes_051520_Box 6](https://user-images.githubusercontent.com/25354670/82084385-746a0a00-96a8-11ea-9275-a9184e3e23f5.png)

**Comment by emily-phet** [comment]
Sim design ended up with a combobox for selecting challenges, which doesn't lend itself to the gift box idea. I like all the gift boxes designed, and will keep this in mind for future sims!
