### ISSUE TITLE
Investigate Tabnine

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1038]
There is a product called https://www.tabnine.com/ which uses machine learning to train on an existing corpus of code to assist in autocomplete using similar patterns.  Now that we have a larger body of code, I wonder whether this could be useful to our team.  Custom training requires "Enterprise" level, which is "contact us for pricing". 

I don't have time to investigate this now, but wanted to write it down in case it proves useful to our team.  Assigning to @ariel-phet for priority/delegation/etc.

**Comment by ariel-phet** [comment]
@brandonLi8 I know you had been learning a bit about machine learning, do you have any interest in looking into this tool a bit and reporting back to the team.

If not, no worries, please assign back to me.

**Comment by brandonLi8** [comment]
@ariel-phet Although this doesn't involve any ml engineering (more of a configuration of software that TabNine made), i'll give it a shot locally. I'll be trying the 14 free trial of the "professional plan."

**Comment by brandonLi8** [comment]
One thing that I'll add right away is that it is super easy to setup for both sublime and vim (both of my editors that I use).

However, @ariel-phet, on https://www.tabnine.com/install, it doesn't look like there is any support for web-storm, which is what I believe most phet devs use.

**Comment by brandonLi8** [comment]
After using TabNine on sublime for about 5 minutes, I noticed right away that it blocks all sublime snippets.

Issue is known by TabNine here https://github.com/codota/tabnine-sublime/issues/11 (still open).

**Comment by brandonLi8** [comment]
I've been using "Deep TabNine Cloud" on sublime for the last 2 weeks. Here's my review:

- Overall, really really good product. Definitely a good time saver!
- Although it blocks sublime snippets, I was able to get around it with setting `autocomplete: true` alongside TabNine.
- There were no performance issues with "Deep TabNine Cloud" on sublime, but I didn't try the free version or other editors/ides.
- I didn't get to use the "Enterprise" option, so I didn't get to "train a model specialized for your code." However, even without this, TabNine picked up on a lot of phet-specific patterns (Property, merge, etc). It also helped with documentation autocompletions.
- Extremely easy to setup, enable, or disable.

Overall, I think this is a huge time saver. I'm going to continue to use the free version once my trial expires.

As @samreid pointed out, custom training requires "Enterprise" level, which is "contact us for pricing". I'm not sure if we necessarily need the "Enterprise" level, since the free version supports training on your personal code (but not on the whole code base). I would recommend devs to individually try the free version. 

@ariel-phet back to you.

**Comment by samreid** [comment]
Thanks for the investigation @brandonLi8, it sounds promising.  I recommend reaching out to TabNine about training the custom model. It would be good to see a baseline price for their "Enterprise" level and whether they can offer any incentives to open source/educational products.

**Comment by ariel-phet** [comment]
Marking for discussion/demo at dev meeting.

@samreid feel free to contact for pricing, however, with the current situation I think it is highly unlikely we would be able to spend much.

**Comment by samreid** [comment]
I reached out to TabNine regarding their Enterprise plan.

**Comment by jessegreenberg** [comment]
8/13/20

@brandonLi8 gave a demo and it looks really nice! He is still using it in Sublime. Anyone that is interested can certainly try it out as well, but we are not going to look into the "Enterprise" plan any further.

Closing this one.
