### ISSUE TITLE
Rename "Self Voicing" to "Voicing" throughout the project

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#1083]
We are renaming the "Self-Voicing" feature to "Voicing". The "Self" was to distinguish from other types of speech output like screen-reader software. But that only makes sense to those within the project that work on both features. "Voicing" is more simple and is a better public facing name fore the feature. Issue will track renaming commits.

**Comment by jessegreenberg** [comment]
Rename was done for documentation and class names. I don't see any hits for 'selfvoicing', 'self-voicing' or 'self voicing' in the project. Sims are running well in local aqua. Closing.

**Comment by zepumph** [comment]
I just checked out `preferences` branches in joist, sun, and friction and found them un-runnable because this rename wasn't propagated there. I'm not sure if that was purposeful or expected, so I'll just pass it to @jessegreenberg to decide, as they are his branches and I'm unsure about their future.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, "self-voicing" removed from new classes in preferences branch.
