### ISSUE TITLE
Localized Character Selection and Supplementation

### ISSUE THREAD

**Issue by RVieyra** [phetsims/tasks#1104]
As part of the Mastercard Foundation grant, we are localizing the character sets for Africa (both an holistic "general Africa" set as well as a "conservative Africa" set).

Please review these selections for each relevant sim as soon as is feasible, preferably no later than Wednesday (Mariah has said she has availability through the rest of the month, but beyond that is iffy). https://docs.google.com/document/d/1xBxZY_P6qb0M5Fsx5fK2Ih04erL47vW5QjyFukEQb54/edit?usp=sharing

**Please comment once you've reviewed.**

The full set of characters from which selections were made can be found here: https://www.canva.com/design/DAE4cZ97Q8g/8KILtJYroCSkaP-4rLgQzw/edit?utm_content=DAE4cZ97Q8g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton (All of these individuals were developed with the support of individuals living in each region of Africa).

**Comment by ariel-phet** [comment]
@RVieyra overall I think these characters look quite good.  A few comments:

1. For Balancing Act, with a character like W11, I think we will need to be careful when considering how she looks sitting, in terms of her dress, to make sure things are looking appropriate. Not an issue with N1 since she is in trousers

2. For Energy Forms and Changes -- are we going to consider a helmet for that character, or is that uncommon enough that we should not have one? Do people not really ride bikes with shorts on -- is trousers more common?

3. For Energy Skate Park -- I like the character set, but I would we try to put them in as athletic of attire as we can "get away with"

4. For Color Vision -- when you add clothing around the neck be careful about having good contrast with the scene selection buttons

**Comment by amanda-phet** [comment]
I think I reviewed this in a meeting already as we discussed specifically how to handle the game levels in the math sims, so unassigning unless you need anything else from me!

**Comment by RVieyra** [comment]
We are just awaiting on Mariah to produce the initial set. I'll close this issue for now, and re-open or create a new issue when we are ready to take any further action. Thanks!
