### ISSUE TITLE
Continuous testing should be mostly green

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1106]
As discussed at today's dev meeting, we would like to invest more resources into getting CT to show more green more of the time so there is less trouble and less noise.  This will take coordination from many developers in fixing sim-specific code, common code, etc, so it is an epic-level issue.  I opened this so it can be triaged and scheduled for 2022 Q2.

**Comment by samreid** [comment]
For instance, here are the red cells from the last 10 columns:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/679486/177418377-42be2975-08bf-4a46-afc4-bb8918a069c0.png">

**Comment by kathy-phet** [comment]
I want check in on how I should interpret the above ... are the only sim-specific repos that currently need attention just the top 9 rows? Should ignore the 7/4 column? Or is 7/4 more accurate because it had more tests done and I should add those rows? (e.g. light versus dark shades). 
buoyancy
center-and-variability
CCK AC 
CCK DC
density
fractions-mided-numbers
gravity-and-orbits
number-play

**Comment by chrisklus** [comment]
It looks like the latest columns finished tests and has similar results to your list above. I think puppeteer is sometimes causing errors that are showing up repeatedly, like the 12:14 column from below. see the error for RIAW - it was the same for the those last 6.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/5618316/177568019-7f2042cb-057a-4196-bcce-b578456219e1.png">

**Comment by samreid** [comment]
I fixed 3 separate CT issues today.

I pushed a proposed fix for the acid-base-solutions CT error in https://github.com/phetsims/acid-base-solutions/issues/174
I also fixed CT error https://github.com/phetsims/nitroglycerin/issues/13
I also fixed CT error https://github.com/phetsims/circuit-construction-kit-ac-virtual-lab/issues/6

**Comment by samreid** [comment]
I pushed a fix for https://github.com/phetsims/build-a-molecule/issues/232

**Comment by samreid** [comment]
After the fixes, my local CT has been been pretty green, I'll put on hold and check again in the coming week.

**Comment by samreid** [comment]
I also fixed https://github.com/phetsims/energy-forms-and-changes/issues/416

**Comment by samreid** [comment]
Since last week, I have fixed or worked around 10 CT issues.  I'll continue monitoring these as I have time.

**Comment by samreid** [comment]
I kept an eye on this again this week and addressed several issues.

**Comment by samreid** [comment]
Nov 17, 2022

Center and Variability: @samreid volunteered himself
CCK: @samreid too
fractions-mixed-numbers: property re-entrant @AgustinVallejo 
number-compare matching tenFrameNode not found!: @chrisklus 
number-play: @chrisklus

**Comment by samreid** [comment]
Here are the last 10 columns with any problems:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/679486/205121941-0d65608b-01c4-415c-9fe3-48ec38ae1cf6.png">

I'll look into the Circuit Construction Kit ones.

**Comment by chrisklus** [comment]
From 12/8/22 dev meeting:

Here is the current state:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/5618316/206544570-9ad61b2d-370a-47dd-99ef-911cc1206585.png">

**Comment by samreid** [comment]
Today's status:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/679486/209199447-6e5d8a36-f3fc-45a4-8952-8d76f08b0321.png">

**Comment by zepumph** [comment]
Today I made some changes that added some metrics to each column, now we can see how many tests are complete and how many are failing:

![image](https://user-images.githubusercontent.com/6856943/235261002-381867ad-ad82-41a1-b06c-6538bb719f30.png)

I hope this helps with this issue. There are ~40 problems on CT right now, but much of that is duplicated, and some of that is because of sparky weirdness that @jonathanolson and I are still sorting out over in https://github.com/phetsims/special-ops/issues/234.
