### ISSUE TITLE
create a code-review checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#130]
This should live in tasks/doc/. I'll describe my code-review process and enumerate the things that I look for. The idea is that this can be used by other developers when preparing their code for review, and when performing a review of someone else's code. This will be a living document.

**Comment by pixelzoom** [comment]
I created the Google doc where I'll start the draft: https://docs.google.com/document/d/16dnSetfnsQAyJpTWm7xocchlL47NcZ3e3qAaOpQtxds/edit

Currently editable by anyone on the PhET team, owned by phethelp.

**Comment by pixelzoom** [comment]
I'm at a good stopping point with this. I don't expect everyone to agree with it, but it's representative of what I consider while doing a code review.

Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
@pixelzoom created a google doc with fleshed out examples and I have created a cut and paste checklist (with a link to the google doc included) here:

https://github.com/phetsims/phet-info/blob/master/code_review_checklist.md

I changed the google doc sharing to be anyone with the link can view

@samreid do you want to put a link to the template in the the development overview? I think that should be sufficient (I think it is OK if there is some duplication between the overview and the checklist). However, if you see anything in the checklist that should be included in the overview it would be good to copy it over.

**Comment by ariel-phet** [comment]
@pixelzoom, @jbphet, @bereaphysics, @jonathanolson, @aaronsamuel137, @samreid 

I have also made this an agenda item to discuss at dev meeting 3/17/2015

**Comment by samreid** [comment]
It is confusing having two very similar documents, with much copy+paste between them--they will be difficult to maintain, difficult to reference, and will get out of sync easily.  I recommend moving the examples from the google doc into the code review checklist MD file, then deleting the google doc.  The examples can be made more concise if necessary (but I don't mind if they are verbose).

**Comment by samreid** [comment]
> @samreid do you want to put a link to the template in the the development overview? I think that should be sufficient (I think it is OK if there is some duplication between the overview and the checklist). However, if you see anything in the checklist that should be included in the overview it would be good to copy it over.

Ideally we will want to align these as much as possible.  Here is one possible plan:
1. Make sure the review checklist covers all of the items currently in the development overview
2. Delete the content from the development overview
3. Add a prominent link from the development overview to the review checklist MD file.

Thoughts from @pixelzoom @ariel-phet @aaronsamuel137 @jbphet @jonathanolson?

**Comment by samreid** [comment]
I have made several updates here (didn't notice these were different repos, so commit messages were not referencing this issue properly):
https://github.com/phetsims/phet-info/commits/master

* Link to anchor for coding style guidelines, see #130
* Added a checklist item "Are there git repository branches that are no longer used and should be pruned?"
* Fixed grammar error, see #130
* Unified quotation marks for query parameters, see #130
* Added checks for internationalization issues, see #130

I'll make sure future edits reference this issue properly.

**Comment by samreid** [comment]
I recommend to rename all usages of the word "imports" and related phrases to "require statements".  Imports are for Java, Python, etc.  OK @pixelzoom ?

**Comment by samreid** [comment]
The relationship between the review checklist and the development overview's "Coding Style Guidelines" is unclear.  Should we move items from the "Coding Style Guidelines" to the review checklist?

**Comment by samreid** [comment]
The review checklist MD file says "Are all imports and constants grouped at the top of js source files, similar to this?" but it doesn't refer to anything.

**Comment by samreid** [comment]
I'm really confused. Multiple times above in this issue thread, it says the checklist should live in tasks/doc.  However, it lives in phet-info.  Is this as intended?  If so, is this issue thread just here vestigially?

**Comment by samreid** [comment]
The Development Process & Checklist significantly overlaps this checklist.  Overlaps should be identified and isolated:
https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.tslwrzmorfdr

**Comment by samreid** [comment]
I'd like to continue my review of the checklist, but would like many of the issues I raised above and overlaps with the PhET Development Overview to be resolved first.  Reassigning to @pixelzoom.

**Comment by ariel-phet** [comment]
@samreid - the markdown file can certainly be moved to tasks. I was writing it up in phet-info for convenience (since that seems to be a good place for in progress stuff), but feel free to move it there.

My main motivation for an actual "checklist" not a google doc is that way one could paste it into a github issue, and actually see the progress (what has been check off and what has not) at a glance. My motivation for taking out the examples was that at some point as people get comfortable the examples will be unnecessary and just clutter. If it is going to be a checklist, it should be succinct and not verbose in my opinion.

**Comment by samreid** [comment]
> @samreid - the markdown file can certainly be moved to tasks. I was writing it up in phet-info for convenience (since that seems to be a good place for in progress stuff), but feel free to move it there.

I wasn't advocating one way or the other, just pointing out a discrepancy.  The developers should discuss the appropriate place--perhaps during the Tuesday meeting.

> My main motivation for an actual "checklist" not a google doc is that way one could paste it into a github issue, and actually see the progress (what has been check off and what has not) at a glance. 

I agree, that is a good reason and it should be a github MD file.

> My motivation for taking out the examples was that at some point as people get comfortable the examples will be unnecessary and just clutter. If it is going to be a checklist, it should be succinct and not verbose in my opinion.

The problem is that the examples weren't just "taken out", but all of the checklist contents were taken out too, and this will cause the problems I described: "they will be difficult to maintain, difficult to reference, and will get out of sync easily".  Perhaps an alternative would be to just link to specific examples without copying all of the checkboxes?

> actually see the progress (what has been check off and what has not) at a glance.

The current MD file already spans > 4 pages on my high resolution monitor.  We will have to discuss what makes sense to include and what makes sense to link externally.

**Comment by samreid** [comment]
> The current MD file already spans > 4 pages on my high resolution monitor. 

By the way, this is not a problem, just want to set the context for what constitutes "at a glance".

**Comment by ariel-phet** [comment]
@samreid actually, it still is at a glance, because when you make checklist issues github gives you a progress bar of how many have been completed, so you can see how many items have been checked without even opening the issue (I find this feature especially convenient).

**Comment by samreid** [comment]
> @samreid actually, it still is at a glance, because when you make checklist issues github gives you a progress bar of how many have been completed, so you can see how many items have been checked without even opening the issue (I find this feature especially convenient).

Yes, I agree completely.  But this progress bar would still be visible/usable whether or not there are verbose examples appearing in the checklist.

**Comment by pixelzoom** [comment]
Answers to @samreid's questions:

> I recommend moving the examples from the google doc into the code review checklist MD file, then deleting the google doc. 

Up to you all to do what you want with this. I was asked to describe what I think about in a code review, and I did that in a Google doc. As I said above - it's what I do, and I don't anticipate that everyone will agree with it. @ariel-phet converted it to a phet-info "check list". I don't think that it lends itself particularly well to a "check list", so I didn't attempt to create one. I put some check boxes in the Google doc at the last minute at @ariel-phet's suggestion.  My preferences would be to have other developers read it, ask me why I do things the way I do, decide which pieces to adopt more generally, and (maybe) end up with a few new things to think about during a code review.  And I think it's way too premature to share with 3rd parties.

> I recommend to rename all usages of the word "imports" and related phrases to "require statements". Imports are for Java, Python, etc. OK @pixelzoom ?

Sure.

> The relationship between the review checklist and the development overview's "Coding Style Guidelines" is unclear. Should we move items from the "Coding Style Guidelines" to the review checklist?

I recommend moving things in the opposite direction. Move "coding style" things out of the code review, so that a step in the code review is "does the code conform to PhET style guidelines?"  Some things in the code-review doc clearly belong in the more general development doc.  They are things that I think are important, that are (were?) missing from the development doc.  Feel free to move the ones that you agree with, ignore the ones you don't find useful.

> The review checklist MD file says "Are all imports and constants grouped at the top of js source files, similar to this?" but it doesn't refer to anything.

This was apparently edit out by @ariel-phet when converting to a phet-info "check list".  See extended example in the code-reviw doc.

**Comment by samreid** [comment]
At today's developer meeting with @jbphet @jonathanolson @aaronsamuel137 and @samreid ( @pixelzoom was out), we agreed:

1. There should be only one file, and it should be the MD file.  Information (including examples) from the Google Doc not present in the MD file will be moved over and @jbphet volunteered to do this.  After it is moved over, the Google Doc can be deleted.
2. There will be a prominent link from the PhET Development Overview to the MD file.
3. There will be a single checkbox in the MD file regarding stylistic issues, which points to a section in the Google Doc for now, since they are more cross-cutting features.  (though we discussed that these may change to checkbox items in the future if they are getting missed or ignored)

@ariel-phet sound OK with you?

Reassigning to @jbphet for the work described above.

**Comment by jbphet** [comment]
I pulled the information from the "PhET code review guidelines" document (https://docs.google.com/a/colorado.edu/document/d/16dnSetfnsQAyJpTWm7xocchlL47NcZ3e3qAaOpQtxds/edit#) into the MD file in GitHub (https://github.com/phetsims/phet-info/blob/master/code_review_checklist.md).  Who should get it next?

**Comment by samreid** [comment]
Perhaps the next step is to discuss with @pixelzoom and/or @ariel-phet at the next meeting.  I'm also still a bit unclear about the relationship between the PhET Development Overview "Coding Style Guidelines" and the Code Review checklist items. For instance, one item in the code review checklist is:

Are names (types, variables, properties,...) sufficiently descriptive and specific, avoiding non-standard abbreviations? Eg:

```js
var numPart  // incorrect
var numberOfParticles  // correct
```

And one part from the style guide in the PhET Development overview is:

Variables should be declared on one line with a separate ‘var’ in front of each.  This makes moving and duplicating lines much easier.  For example,
```js
var x;
var y;
```
and not
```js
var x, y;
```
or
```js
var x,
y
```

Where do we draw the line?  Why do we need a line at all?  Shouldn't some of the items in the "code style" be review checklist items?  The argument that the Code Style issues were cross-cutting doesn't seem to apply since many of the checklist items also must be cross-cutting.

Other good next steps for this issue would be for developers (me included) to take it for a test drive  when performing upcoming code reviews and we can iterate from there.

**Comment by pixelzoom** [comment]
If the Google Doc is going away, then the first line of the MD file should be deleted:

> For further info and examples on each checklist item see the PhET Code Review Guidlines

**Comment by pixelzoom** [comment]
My 2 cents on style guidelines... 

PhET Development Overview is currently the "go to" place for PhET-specific style guidelines. The "Codings Style Guidelines" section starts with:

> For general coding, please follow the guidelines set out in idiomatic.js (https://github.com/rwldrn/idiomatic.js/).  Some PhET-specific differences from and additions to this spec are:

So I think it makes sense to put all PhET-specific style guidelines in the PhET Development Overview, and have the Code Review check list ask "Does it follow the PhET coding style guidelines?"  It will also be easier to modify the style guidelines without having to modify the Code Review check list.  And it will keep the size of the Code Review check list manageable.

**Comment by samreid** [comment]
I understand your recommendation but not sure why something like

```
Are names (types, variables, properties,...) sufficiently descriptive and specific, avoiding non-standard abbreviations? Eg:

var numPart  // incorrect
var numberOfParticles  // correct
```

is a checklist item and not a coding style item.  Can you clarify for this case and generalize?

**Comment by pixelzoom** [comment]
As I said in https://github.com/phetsims/tasks/issues/130#issuecomment-81967846, I recommend moving "coding style" things out of the code review and into the "Coding Style Guidelines" section of the PhET Development Overview. They are in the checklist only because I didn't see them in the "Coding Style Guidelines", and wanted to remember to discuss them.

So the example immediately above, along with everything else in the "Coding conventions" heading of the MD file, should be moved to "Coding Style Guidelines" section of the PhET Development Overview. (Assuming that everyone agrees that they are guidelines that PhET wants to follow.)

**Comment by pixelzoom** [comment]
Btw... This whole topic would have been a whole lot easier if y'all had waiting until I was done being sick. I guess I didn't realize that it was such a high priority.

**Comment by samreid** [comment]
Well, I am still trying to figure out which other items in the checklist count as "code style" items, but happy to wait to discuss this in person, there is no hurry on my behalf.

**Comment by pixelzoom** [comment]
I wil migrate “style” things to “PhET Development Overview”.

**Comment by pixelzoom** [comment]
At 3/26/15 dev meeting, @ariel-phet requested something like this at the very top of the checklist:

> Prior to doing a code review, copy this checklist to a GitHub issue for the repository being reviewed.
If a code review is part of a third-party contract, create that GitHub issue when the repository is created, so that the GitHub issue matches the checklist agreed upon in the contract.

**Comment by pixelzoom** [comment]
Style items have been moved to “PhET Development Overview”.  Note has been added to the top of the checklist. 

@ariel-phet @samreid @jonathanolson @jbphet @aaronsamuel137 @bereaphysics please let me know if other changes are needed.  Once this is finalized, we should probably announce this checklist and change to the "PhET Development Overview" document to the Google group.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to decide how to proceed. Should the checklist and changes to the "PhET Development Overview" document be announced to the Google Group? Anything else that needs to be done?

**Comment by pixelzoom** [comment]
4/23/15 developer meeting consensus:

• For internal code reviews, copy the code-review checklist to a GitHub issue titled "code review".  Do this when it's time to do a code review.

• For 3rd-party contracts, copy the code-review checklist to a GitHub issue titled "code review". Do this at the time that the contract is negotiated. 

Nothing else to do at this time, closing.
