### ISSUE TITLE
Investigate Chrome Web Store

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#152]
Apparently there is a "chrome web store" that would allow us to easily make our sims more discoverable for chromebooks. We should look into this possibility as soon as possible.

@oliver-phet could you gather more info. Perhaps have @arnabp see the steps involved in making a chrome web app.

**Comment by arnabp** [comment]
Uploading apps to the Chrome Web Store is actually really straightforward. The "developing" is done outside and they only require the URL of the applet, along with a .json with app info, a screenshot, a promotional image, and a logo. 

So from this it looks like we would only be able to put up the HTML5 sims. We'd also need dedicated logos, but my idea is that we can just take single elements from each sim, add the Phet logo, and those would make for good logos. The promotional image can (I think) be the same for all of them, so that wouldn't be too hard either.

**Comment by oliver-phet** [comment]
It is looking like we would be able to at least add our HTML5 sims and perhaps our Flash sims. 
We'll need to decide on the structuring - do we want one "app" with all of the HTML5/Flash sims. Or one *per* sim?

**Comment by ariel-phet** [comment]
We likely will want both. Can we find out how big (pixel by pixel) size the logos are? We will likely want to get @alexklinger involved in this project eventually.

**Comment by ariel-phet** [comment]
@arnabp - can you investigate the requirements for the logos (pixel by pixel size being the main constraint)? Please report in this issue and assign back to me. Thanks!

**Comment by oliver-phet** [comment]
@ariel-phet - arnabp and I were going to post a "test" sim (probably ESPB) for internal testing. We were just going to hack together some test images at the correct dimensions (this test app will not be publicly available).
Here is the getting started info: https://developer.chrome.com/webstore/get_started_simple

**Comment by ariel-phet** [comment]
Ah, excellent

**Comment by arnabp** [comment]
I saw this as an option when publishing a sim, we may want to look into this.

Opt in to include this item in <a href="http://developer.android.com/distribute/googleplay/edu/index.html">Google Play For Education</a>. By opting in, you agree to the ,<a href="https://developer.chrome.com/webstore/play_edu_tos">Google Play for Education Developer Terms and Conditions</a>.

**Comment by arnabp** [comment]
There is also an issue I am running into when I trying to create packaged apps (which will give us offline support) instead of hosted apps (which must be online). 

Running the app gives me this console error
```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```
Researching this has led me to find out that Chrome Web Store apps don't support inline javascript. I went ahead and isolated all the inline javascript codes to these: 
![screen shot 2015-02-03 at 4 54 59 pm](https://cloud.githubusercontent.com/assets/8583364/6032366/6fbf74dc-abc5-11e4-8244-2113f4469cff.png)

Is there anything we can do about this?

**Comment by oliver-phet** [comment]
@jonathanolson @samreid Do you guys have any insight in to this? 
Here is the relevant content security policy: https://developer.chrome.com/extensions/tut_migration_to_manifest_v2#inline_scripts

**Comment by jonathanolson** [comment]
Looks like the way we build sims into one file isn't allowed. It would presumably require us to have an additional way of building sims.

I'll add it to discuss briefly in the developer meeting.

**Comment by pixelzoom** [comment]
How about just publishing a "PhET Interactive Simulations" app that links to the PhET website. This is what Khan Academy and others have done.  Do that as a first step, and see if PhET gets any traffic before committing resources to publishing individual sims.

**Comment by ariel-phet** [comment]
At the moment, the current plan would be to make an android app similar to what we have done as an iPad app that bundles the sims, and allows offline use. Closing
