### ISSUE TITLE
design README.md for published sim repos

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#159]
See https://github.com/phetsims/tasks/issues/144

@ariel-phet requested @samreid to make a rough draft and discuss it with other developers on Tuesday.

@pixelzoom 
suggested
Title
Blurb

**Comment by samreid** [comment]
Questions: how much should go in README vs in the PhET Development Overview.

Add language for accessing 3 things: master, SHA, and iframe

**Comment by samreid** [comment]
I've created an initial draft for review here: https://github.com/phetsims/forces-and-motion-basics  I'll add it to Thursday's agenda for discussion, but let me know if you have any suggestions/improvements in advance.

**Comment by pixelzoom** [comment]
Initial draft looks great, thanks for doing this. 

A few notes/questions/suggestion:

(1)  "PhET Development Overview" link is broken in both places ("Page not found").

(2) For this sim, it says "an educational physics simulation in HTML5".  The question I have is whether it's necessary to say "physics".  If so, we'll need to substitute "chemistry", "math", etc. as appropriate. And I can see that resulting in copy-paste errors. And it makes it more tricky to automatically generate this file, if that's in the plans.

(3) I find sentences like `Launch Forces and Motion: Basics` unnecessarily difficult/ambiguous to parse, especially for sim titles that include ':'. How about putting quotes around the sim name, so the general form would be `Launch "Forces and Motion: Basics"`.

(4) Put the `Launch "sim name"` link above the screenshot. It's easy to miss it below the screenshot.

(5) Step (1) of the "Quick Start" is very sim-specific. The first clone is the sim's repo, and the others are its dependencies. I can see this becoming out-of-sync with the sim's actual dependencies (as config.js and package.json frequently are now).  So unless README.md is going to get automatically generated by the build process (which is problematic, see 2 above), we might want to consider whether the "Quick Start" section is necessary, or at least reconsider step 1. 

(6) Instead of putting "GPL" for the license, put a link to the LICENSE file, in case licensing changes in the future.

**Comment by samreid** [comment]
Maybe generate this dynamically on a rebuild?  Version can go in there.

**Comment by pixelzoom** [comment]
I'll take a look at writing a grunt task, after template has solidified.

**Comment by samreid** [comment]
Sorry to add work, but it may make a lot of sense to work on the automatic generation of *_en.html pages while working on that.

We may also want to automatically generate the *config.js files as well.

**Comment by pixelzoom** [comment]
... and version.js (until we remove it.)

**Comment by samreid** [comment]
I addressed @pixelzoom comments above.  Regarding:

> (5) Step (1) of the "Quick Start" is very sim-specific. The first clone is the sim's repo, and the others are its dependencies. I can see this becoming out-of-sync with the sim's actual dependencies (as config.js and package.json frequently are now). So unless README.md is going to get automatically generated by the build process (which is problematic, see 2 above), we might want to consider whether the "Quick Start" section is necessary, or at least reconsider step 1.

I left it as is since I think it is important that the developer can copy all the commands in a single block, and we are discussing automatically generating these.

**Comment by pixelzoom** [comment]
@samreid I think it's fine to leave "Quick Start" as is, as long as we have a grunt task to auto-generate the README, and that task is run every time we do a build. 

@ariel-phet @oliver-phet @jbphet @jonathanolson Any more feedback on the content or process? I'm not going to start on the grunt task for auto-generating README until you've weighed in.

**Comment by pixelzoom** [comment]
Priority set to medium, which means sometime in the next 2-3 weeks. @ariel-phet feel free change to priority if you want it done sooner.

**Comment by pixelzoom** [comment]
@samreid wrote:
> Sorry to add work, but it may make a lot of sense to work on the automatic generation of *_en.html pages while working on that. We may also want to automatically generate the *config.js files as well.

@pixelzoom wrote:
> ... and version.js (until we remove it.)

Generating the README has no dependencies on any of these other auto-generation tasks, it is self-contained. Auto-generating those things is the subject of https://github.com/phetsims/chipper/issues/63 and https://github.com/phetsims/chipper/issues/74. And I will definitely *not* be addressing those issues as part of this issue.

**Comment by jonathanolson** [comment]
FAMB example looks great to me.

**Comment by ariel-phet** [comment]
I made some slight wording changes about the Development Overview, but otherwise all looks good to me.

**Comment by oliver-phet** [comment]
Looks good to me.

**Comment by jbphet** [comment]
The readme file itself, as demonstrated in the FAMB example, looks fine to me.  I made a couple of minor edits to the section of the PhET Development Overview document that talks about getting stable code.

**Comment by pixelzoom** [comment]
What did we decide the README should look like for:
• sims that have not yet been published? 
• common-code repos?

**Comment by jonathanolson** [comment]
> • common-code repos?

It probably depends a lot on the specific common-code repo.

**Comment by samreid** [comment]
Perhaps we should put together a working example for Joist (typical PhET repo) and for Scenery (custom PhET repo).  Anyone feel free to start on this or let me know if I should do so.

**Comment by pixelzoom** [comment]
One of the things that must be filled in is the sim *description* ("Explore the forces at work in a tug of war...")  For Java/Flash sims, the description originally lived in the strings file. It was later removed from the strings file (and About dialog), and made the responsibility of the website. That said... The description currently does not live anywhere in the sim repo. And perhaps it shouldn't, for the same reasons that it was moved out of the Java/Flash sims.

Questions:
1. Is the description necessary in this template?
2. If it is necessary, where should it reside? (It must be accessible by the grunt build process.)

**Comment by pixelzoom** [comment]
Design of common-code README.md moved to https://github.com/phetsims/tasks/issues/180.

**Comment by pixelzoom** [comment]
@ariel-phet @oliver-phet @samreid @jonathanolson @jbphet Opinions on https://github.com/phetsims/tasks/issues/159#issuecomment-75851874 please.

**Comment by samreid** [comment]
I do like how the blurb appears in https://github.com/phetsims/forces-and-motion-basics -- would feel a bit bare without that blurb text.  Perhaps it could appear in the package.json as "blurb".  But to answer your direct questions:

> 1. Is the description necessary in this template?

I would categorize it as desirable rather than necessary.

> 2. If it is necessary, where should it reside? (It must be accessible by the grunt build process.)

Package.json seems straightforward, but other places may make sense as well.

**Comment by pixelzoom** [comment]
If it lives in package.json, how will the website get it?  How will it get translated? We should avoid having it live in both package.json and the website database, it will likely get out of sync.

**Comment by pixelzoom** [comment]
If it needs to be in the template, then I think (a) it needs to be in the strings file, (b) it needs to be translated using Rosetta, and (c) the website needs to get the translated string from the sim.

I would prefer to see it go away, and make the description live solely on the website, as we did for Java/Flash sims.  Doing a lot of work so that it can in the repo README.md is misplaced effort.

**Comment by samreid** [comment]
Here are my preferences (top=first preference), but I'd like to hear from @ariel-phet @oliver-phet @jonathanolson @jbphet as well.

1. Include english-only blurb text in the sim README.md files, and run the risk that sometimes they may be out of sync with what appears on the website
2. Don't include blurb text in the README file
3. Invent a complex, expensive or brittle system that lets the text appear both places and keeps it synchronized.

**Comment by jonathanolson** [comment]
Some thoughts:
1. We shouldn't have to deploy a sim to update the description.
2. We'll need templates for repos that aren't published yet, and presumably don't have descriptions.
3. I'd prefer having a completely separate description in package.json for the template, as our description for (presumably) primarily developers may differ from the description for teachers/students.

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> 3. I'd prefer having a completely separate description in package.json for the template, as our description for (presumably) primarily developers may differ from the description for teachers/students.

(1) The description has (up until now) been described as the same description that appear on the sim's website page. Why do we need a description that's specific to developers? Why can't they just visit the PhET website (via the link provided in the template) to have a look at the sim?

(2) By "may differ" it sounds like having a developer-specific description would be the exception, rather than the typical case. If it's not the typical case, then that means in most cases we'll be duplicating the website description in package.json, where it will not be translatable. And we are creating more work, for (imo) very little return.

So... I think a developer-specific description is unnecessary, and should be avoided.

Still waiting for feedback on the 'description' issue from @jbphet, @ariel-phet and @oliver-phet.

**Comment by ariel-phet** [comment]
I suppose the operative question for me becomes "who is the description for" -- ie, what is the use case? On the website it is really for teachers/students.

I assume (but perhaps I am wrong) that the main use case is a developer who is already familiar with our simulations is visiting our repos to look at the source code. Our descriptions tend to be "touchy feely" and not really styled towards this use case.

If people agree this use case is the main one, I would be in favor of dropping the description altogether.

More importantly, I think we can make a simple compromise, which is once we have HTML5 sim pages, we can just change to linking to the sim page, instead of directly to the simulation, with text that say something like:

"For a description of this simulation, associated resources, and a link to the published version go to ......"

**Comment by jonathanolson** [comment]
I'm fine dropping the description then.

**Comment by samreid** [comment]
I'd be okay with testing out the compromise @ariel-phet described, pointing to the simulation page.

**Comment by pixelzoom** [comment]
I implemented a `generate-published-README` grunt task, and took a few liberties tweaking the README format. Here's an example of the output: https://github.com/phetsims/reactants-products-and-leftovers.

This task is *not* integrated into any of the other tasks, because it's intended only for published sims. So until we have a `deploy-production` task, you'll need to run this manually.

@ariel-phet @samreid @jbphet please provide feedback.

**Comment by pixelzoom** [comment]
A question: Do we want any of the links in README.md to open in a new tab/window? My opinion isn't too strong, but while developing this, it felt like all of the links should open in a new tab/window.

**Comment by pixelzoom** [comment]
We have not decided what the README should look like for unpublished sim repos. I've moved that to issue https://github.com/phetsims/tasks/issues/185.

**Comment by pixelzoom** [comment]
A bunch of commits for this issue were accidentally tagged as being associated with phetsims/chipper#159. I'm not going to try to mention them all here. The files that are relevant are:

```
chipper/js/grunt/Grintfile.js
chipper/js/grunt/generateREADME.js
chipper/templates/README-published.md
chipper/templates/README-unpublished.md
```

**Comment by ariel-phet** [comment]
I think it would be appropriate for links to open in a new tab/window, since all the links lead away from github.

**Comment by pixelzoom** [comment]
All links now open in a separate tab/window.

**Comment by pixelzoom** [comment]
Notes from 3/10/15 developer meeting:

• Delete step 4 in “Quick Start”
• Move steps 5 & 6 under a new “Get Involved” heading

**Comment by pixelzoom** [comment]
All changes incorporated, see https://github.com/phetsims/reactants-products-and-leftovers for an example.  Updating the README for all published sims will be done in https://github.com/phetsims/tasks/issues/186.

Closing.

**Comment by samreid** [comment]
The changes from today's meeting look great, nice work @pixelzoom.
