### ISSUE TITLE
RC testing for Molecule Shapes 1.0.0-rc.1 & Molecule Shapes: Basics 1.0.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#179]
"Molecule Shapes" and "Molecule Shapes: Basics" are ready for their release-candidate testing.

Release candidates:
http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-rc.1/molecule-shapes_en.html (regular)
http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.0.0-rc.1/molecule-shapes-basics_en.html ("Basics")

Test matrices:
https://docs.google.com/spreadsheets/d/1wfA1SVvOKK-d26ozNNeGDuuq5OtUpInGcEkfK_Eqvgg/edit (regular)
https://docs.google.com/spreadsheets/d/1pfJglrdMScIyruOXQilQiNse91tGhafQKLouOJISSMY/edit ("Basics")

If an issue is present in both simulations, please just make an issue for the main sim (https://github.com/phetsims/molecule-shapes/issues). Canvas performance (boxy appearance and warning displayed on sim launch) is likely to be less than ideal on tablets (see https://github.com/phetsims/molecule-shapes/issues/102).

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @phet-steele @arnabp please make this your top testing priority

**Also Note** the testing matrix now includes a section at the bottom for "other tests" -- such as testing that the download file works, and the iframe works. Since both these solutions were robust, they only need to be tested on the platforms listed.

**Comment by ariel-phet** [comment]
It appears there is good testing coverage for this task and a new RC is necessary. Closing the test issue
