### ISSUE TITLE
Look into privacy of youtube videos

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#181]
Hey @arnabp, you might already know the answer to this.. but is there a way to make a video "unlisted" but with even higher privacy? For instance, if we embed the video in a webpage, the user would not be able to click back to YouTube or see the URL and pass it on to someone else (they would only be able to access/see the video on the webpage).

**Comment by arnabp** [comment]
The other privacy setting above unlisted is private, which requires users to be directly invited by the creator via email to view the video. I'm not sure how well these translate to embedding and what restrictions we can place on embedded videos though, I can look into that on thursday.

**Comment by ariel-phet** [comment]
@aaronsamuel137 mentioned that vimeo might be another option. 

@arnabp can you look into the pricing structure for vimeo as a video host?

**Comment by arnabp** [comment]
Vimeo pro lets us customize the video to remove any backtrace links and lets us keep the video private and unlisted. Vimeo plus lets us remove the links but the video will still be listed on their site. 

Vimeo Pro: $200/year
Vimeo Plus: $60/year

**Comment by oliver-phet** [comment]
Is there any limit to the amount of videos we could upload using either account?

**Comment by arnabp** [comment]
On Pro we can add a maximum of 20 GB of video each week. On Plus it's 5 GB per week

**Comment by ariel-phet** [comment]
20 GB a week is a pretty serious amount of video...let plan on discussing these options with @kathy-phet

**Comment by ariel-phet** [comment]
In an email referring to some of the issues with youtube @oliver-phet said:

"Yes, the plan would be to set the videos as ‘private’ so that they wouldn’t be searchable. However, users could watch the video on the sim pages and right-click the video to get the video url (or click the youtube text to take them to the video on youtube). Hiding the navigation also hides the pause/play buttons and this might not be preferable. We should test to see what it looks/behaves like on an iPad too."

**Comment by ariel-phet** [comment]
@kathy-phet said she would like to try the vimeo route first (the price seemed very reasonable to her)

@oliver-phet - please go ahead and set up a vimeo pro account for us

**Comment by oliver-phet** [comment]
Vimeo account is setup. Info is on Unfuddle>External Account Info

**Comment by oliver-phet** [comment]
@arnabp Can you test out uploading a 'private' video so that @aaronsamuel137 can test embedding it into the website?

**Comment by arnabp** [comment]
@aaronsamuel137 This is the HTML embed code for a test video I made. Can you test this on a HTML5 sim page primer?

iframe src="https://player.vimeo.com/video/123764106" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe
(insert brackets before and after)

**Comment by aaronsamuel137** [comment]
Sorry, I forgot to comment on this last week, but the vimeo video is working great. You can see it now being tested on the new sim pages: http://phet-dev.colorado.edu/en/simulation/area-builder

I would say that we can go ahead with vimeo.

The only remaining privacy concern is that the way the page is set up now, somebody still could technically get the video link by viewing the page source - even when they are not logged in. I doubt most teachers would go through the trouble to do that however.

If this is an issue, I see two ways around it:

1. Don't show the video at all unless someone is logged in.
2. Just show a screenshot of the video instead when they are not logged in. (This option is more work since we'll have to take screenshots of every video and host them somewhere ourselves).

**Comment by ariel-phet** [comment]
Hey @aaronsamuel137 - good to hear!

I am going to move your comments to a website issue and close this one.
