### ISSUE TITLE
Install Google Chrome browser on Intel Education tablet

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#189]
Hey @arnabp when you get a chance in the nearish future can you figure out how to install Chrome on the Intel Education tablet I gave you.

**Comment by arnabp** [comment]
So after playing around with the tablet for a while, I don't think I can install Chrome on the tablet without seriously diving into the software, either by rooting the device or by clean installing a different ROM. So I ask, what exactly are we trying to do with the tablet? Are we testing our sims specifically for this tablet, because then we're stuck to the default browser. Are we testing chrome on this hardware, in which case I might be able to root the device (I have my reservations as to whether this is actually possible for this device). Or do we just want another android testing device, in which case I can simply clean install stock android.

**Comment by ariel-phet** [comment]
Let me get @kathy-phet to give input here

**Comment by ariel-phet** [comment]
This issue has been moved to a private repo for discussion
