### ISSUE TITLE
Research good headset (high quality mic)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#190]
@arnabp Can you look into some good microphones for recording audio. Something "hands free" would be ideal - maybe a headset, but look into desktop mics also. Maybe some regular youtuber's have recommendations on mics they record with?

**Comment by arnabp** [comment]
The <a href="http://www.amazon.com/Blue-Microphones-Snowball-Condenser-Microphone/dp/B006DIA77E/ref=sr_1_1?s=musical-instruments&ie=UTF8&qid=1426112379&sr=1-1&keywords=blue+snowball"> Blue Snowball </a> is easily the best relatively inexpensive desktop mic.

If we want to go more toward studio grade there's the <a href="http://www.amazon.com/Blue-Microphones-Yeti-USB-Microphone/dp/B002VA464S/ref=sr_1_5?s=musical-instruments&ie=UTF8&qid=1426112474&sr=1-5&keywords=blue+snowball"> Blue Yeti </a>. I'm assuming this is for testing interviews, so this might be overkill.

If we already have headphones, <a href="http://www.modmic.com/collections/frontpage/products/modmic-4-0"> ModMic </a> has great quality attachable microphones.

**Comment by samreid** [comment]
@pixelzoom may also have some good suggestions here.

Also, I have a Shure XLR with mic stand that isn't doing anything at the moment, but it requires XLR to USB adapter.  Let me know if I should bring it in.

Also, in my experience, MacBooks/iPads/iPhones are pretty great with audio recording.

**Comment by pixelzoom** [comment]
For "recording audio" is a little vague, but I'll assume that you want to record voiceovers and conversations. Unless you want to mess around with an audio interface, you'll want a USB mic.

Two important considerations:

(1) What pattern do you need? Microphones have different response "patterns". Some are unidirectional, some are omni-directions. If you choose the wrong one for the job, you'll be very disappointed. (And I can't recommend a pattern, because you haven't specified what "the job" is.)

(2) Make sure that your recording program and platform are supported.  For example, some USB mics will only work with some apps on iPad (usually GarageBand).

That said...

+1 for Blue Snowball, http://www.bluemic.com/snowball/. Though some people might not like the shape of it, it's not shaped like a traditional mic.

Other nice products:

• Blue has full line of USB mics, see http://www.bluemic.com/desktop/
• Apogee "Mic 96", http://www.apogeedigital.com/products/mic
• Audio-Technica A-T USB, http://www.audio-technica.com/cms/features/2e1bc0bd5dccd5fb/index.html

**Comment by pixelzoom** [comment]
@samreid wrote:
> Also, in my experience, MacBooks/iPads/iPhones are pretty great with audio recording.

Again, don't know what you're trying to do with this. But I agree with @samreid here. Have you tried recording with the built-in mic on a Mac device?

**Comment by ycarpenterphet** [comment]
@oliver-phet, is this the mic we would be ordering for recording video primers? Or is this a different conversation?

If this is the one for video primers (and other content we'll publish to the website), our biggest priority is good audio quality that minimizes background noise while recording sim actions and voiceover narration in Camtasia.

Using the macbook's internal microphone sometimes has caused us problems due to the pickup of substantial fan noise from the laptop, as well as recording loud mouse clicks etc. This is why an external mic would be ideal.

**Comment by schasteen** [comment]
I agree with YY.  We want something that is hands free, because the person recording will be manipulating the simulation.  We want something that is close to the mouth, to minimize noise from the computer fan and have a nice warm feel.  I have a personal headset that I use for Skype which works well (but it's old, so we want something newer that can live at PhET for others to use).   So, I would guess a cardioid pickup pattern but really am not sure what sort of pickups these computer headset microphones have.  

Have you used the blue snowball, do you know if it will be close enough to the mouth?  I was going for a headset so that the person recording wouldn't need to lean over to a desktop mic.  

Is that enough information for a recommendation?

**Comment by arnabp** [comment]
You can move the blue snowball pretty close toward the person's mouth but it is fairly large like most desktop mics and might get in the way of the person attempting to use the sim. 

Most headsets are either too expensive or come with very subpar microphones. So <a href="http://www.modmic.com/collections/frontpage/products/modmic-4-0"> ModMic </a> is probably your best option for a good quality mic that you can just attack to a pair of headphones we already have.

**Comment by schasteen** [comment]
This looks fine to me.  Go ahead and order this, but be sure to get the USB adaptor that they say will be needed for a Mac.


On Mar 13, 2015, at 3:52 AM, arnabp <notifications@github.com<mailto:notifications@github.com>> wrote:


You can move the blue snowball pretty close toward the person's mouth but it is fairly large like most desktop mics and might get in the way of the person attempting to use the sim.

Most headsets are either too expensive or come with very subpar microphones. So ModMic <http://www.modmic.com/collections/frontpage/products/modmic-4-0> is probably your best option for a good quality mic that you can just attack to a pair of headphones we already have.

**Comment by oliver-phet** [comment]
Which mic should I purchase? There were many options mentioned in this thread.

**Comment by schasteen** [comment]
My response to the thread is above, in response to @arnabp suggestion of the ModMic.  @arnabp, you were suggesting the ModMic out of all the options that had been listed, correct?  I assume you had looked at the options that pixelzoom had mentioned?

Here is what I wrote:  This looks fine to me.  Go ahead and order this, but be sure to get the USB adaptor that they say will be needed for a Mac.

**Comment by oliver-phet** [comment]
I would assume the ModMic also requires a pair of headphones to be functional since it doesn't have a stand. Does PhET have headphones that will be used with this mic?

**Comment by schasteen** [comment]
I don't know offhand. If not, then please get a set.  They don't need to be great, just functional.

**Comment by pixelzoom** [comment]
ModMic has a uni-directional pattern, so it's will pick up mainly the person (interviewee?) speaking directly into it, and very little of anything else (e.g. , the interviewer).  Just wanted to point that out, because I'm still not clear on what the use cases are for this purchase.

**Comment by oliver-phet** [comment]
@arnabp I talked with @ycarpenterphet about this and this mic is (primarily) being used for sim primer voice recording. We basically need something that is Mac/PC compatible, records voice well, and picks up little/no background noise. The idea would be that anyone recording a sim primer could use this mic to get consistent audio for the videos.
It could be a headset or desktop mic - whichever meets the requirements above the best.

**Comment by arnabp** [comment]
Both the snowball and the modmic are good. The general consensus is that Snowball has higher quality but also picks up background noise much more easily. You said we want something that picks up little to no background noise so maybe the Modmic is the preferable option. But if we're recording in quiet rooms then Snowball would be the better option, so it depends on the recording environment.

If we need a headphones to go along with the modmic there are <a href="http://geni.us/30Vr">many</a> <a href="http://geni.us/2KEH">many</a> <a href="http://geni.us/z2e">many</a> <a href="http://www.amazon.com/gp/product/B002LBSEQS/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1">many</a> good options we can go with.

**Comment by schasteen** [comment]
@arnabp, I just want to confirm that you are recommending the Snowball and Modmic out of all options that were listed, including the suggestions from pixelzoom?

The main reason for getting an external mic is because of fan noise from the computer.  (Running Camtasia plus simulations typically puts a big load on a computer, and it runs the fan at high speed).  Thus, I veto the Snowball, I want something close to the mouth.  It sounds to me, still, that Modmic is the best option but I want to confirm that @arnabp's recommendations are drawn from the broad range of possibilities.  It does seem odd to me that there isn't a good quality headphone mic, and we have to patch together a solution.  But if that's the way it is, then that's fine.

**Comment by amanda-phet** [comment]
@oliver-phet bought [these] (http://www.amazon.com/Sennheiser-202-Professional-Headphones-Black/dp/B003LPTAYI) headphones for me and they seem to work just fine.

**Comment by arnabp** [comment]
@schasteen Yes. The suggestions from Pixelzoom are all great mics too but have too main issues being that a) they're not made necessarily for noise cancellation and b) they are significantly more expensive at audio levels that make only small differences. While it may be odd that we have to "patch together" the mic and the headphones, most of that is at the fault of the video gaming community, which now dominates the market for headsets but buys into expensive headsets with extremely subpar mic quality. If it helps, I bought this mic for myself this past week (the timing here was great, I was researching into mics already when Oliver posted this issue) and I can bring it in next Tuesday if anyone wants to test it out.

@amanda-phet Those headphones seem fine. Though I would say they look a little bass heavy, I suppose we don't exactly need top notch sounds reproduction for what we're trying to accomplish.

**Comment by schasteen** [comment]
This is great information, thanks.  I suggest @oliver-phet gets the mod mic, adaptor, and headphones, unless anyone disagrees.

**Comment by oliver-phet** [comment]
@arnabp I won't be here next week, but I think it would make a lot of sense to test the audio recording with your mic. Maybe you could coordinate with @schasteen and test? If they work, then Stephanie or I can purchase.

**Comment by schasteen** [comment]
@arnabp, email me directly at stephanie.chasteen@colorado.edu.

**Comment by arnabp** [comment]
I made this video and recorded the audio using the modmic that I bought for myself if you wanted a reference: https://youtu.be/n1AKnZJBzdw

This was recorded in Oliver's office (where the AC was being quite loud), but I also turned on iMovie's basic background noise remover.

**Comment by oliver-phet** [comment]
Headphones, mic, and mac adapter ordered 3/31

**Comment by arnabp** [comment]
Headphones, mic, and adapter have all been connected and bundled together on Oliver's desk.
