### ISSUE TITLE
Create Spreadsheet of Gold Star Activity Authors

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#241]
From @patricialoeblein:
Go through all the activities presently on the live website. We need a spreadsheet that would have the author’s name and email and also if they have one or multiple gold star activities. No need to include any PhET authors. There should be about 60 GS authors. Once the spreadsheet is filled, email each one to make them aware of  recent PhET changes.

**Comment by amanda-phet** [comment]
@patricialoeblein didn't you start a spreadsheet with a lot of this information? Just checking because it may help @phet-steele  to start with the work you already put in.

**Comment by patricialoeblein** [comment]
My spreadsheet has lots of information that is not relevant. Also, since other people have been receiving the notifications, I have not kept track of all Gold Star authors as thoroughly as I had in the past. I think having a fresh spreadsheet will be helpful for several purposes; we have added a few columns. Also, Steele has found a quick way to identify all authors, so we will be starting with a fresh accurate set of data.

**Comment by phet-steele** [comment]
Spreadsheet made! Next step is to email.

**Comment by amanda-phet** [comment]
Great! I think we are still working on what that email will say. Stay tuned.

**Comment by patricialoeblein** [comment]
Thanks. Also, we won't email until the sim pages, activity upload, and profile management are fully working.

**Comment by phet-steele** [comment]
All emails sent on 6/26

**Comment by patricialoeblein** [comment]
thanks for doing this. I will keep track of replies on the spreadsheet.
