### ISSUE TITLE
When testing edge, we should test whether offline loads are faster

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#273]
See https://github.com/phetsims/joist/issues/164

@ariel-phet can you assign a tester to (a) download a recent sim for offline use and (b) launch with Edge and report if the same symptoms in joist#164 are observed?

**Comment by ariel-phet** [comment]
@arnabp - since you have the windows 10 computer can you download an html5 sim (I think Molecule Shapes would be a good candidate) and see how long it takes to open the downloaded sim with Edge?

Currently, if you download an HTML5 sim and open it with IE11, it takes over 20 seconds to load (and usually is just a blank webrowser until the sim loads). We want to see if there is any improvement with Edge.

**Comment by arnabp** [comment]
Both IE11 and Edge on Windows 10 are having very variable opening times. Sometimes it takes the 20 seconds to load with the blank screen and other time is loads almost immediately.

**Comment by ariel-phet** [comment]
@bryo5363 can you check this on your computer and edge, and report back, should be an easy test.

**Comment by bryo5363** [comment]
Yep I've got a decent block of class but I will let you know ASAP

**Comment by bryo5363** [comment]
I tested Molarity 1.2.0-rc.2 offline and I did not notice the string loading issue that was present when I was online. The loading time was much faster as well.

**Comment by ariel-phet** [comment]
Thanks @bryo5363
