### ISSUE TITLE
Grind through non-English activities looking for junk

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#284]
@elisemorgan - this is a bit of a "grindy" task, but would be good to chip away at.

Basically go through all the non-English activities and look for junk. For instance, a few times people have uploaded things like resumes and such. @patricialoeblein has requested we go through all non-English activities and look for these kinds of abuses.

Probably the easiest thing to do would be to sign in to the website, go to the administrative functions and click on "activities" - which will give you the full list of all activities.Then open each non-English activity and just see if it is obviously junk. 

Also make a google doc that lists the name of any user that has uploaded a junk activity so we can deactivate their account.

Let me know if you have any questions or if the directions are unclear.

**Comment by patricialoeblein** [comment]
There have been 2 issues in the last few weeks that have instigated this ticket. In both cases, I have emailed the author and politely told them that they have posted incorrectly. I will include the emails below. One activity had a PhET teachers' Tips as the uploaded file, so wondered if there was a language barrier. The other had a resume. I think we should continue to email authors and help them understand why we deleted their activity. In the beginning of the database, there were malicious files like ".exe" or "jnlp" ; these are automatically not allowed anymore. I like the idea of documenting the deleted author activities and I think we want to include a reason like incorrect or corrupted file or inappropriate. I occasionally encounter these types of problems in the english activities as well and I think it would be good to have a central repository. 
As for emailing the authors, I can continue that responsibility. Please share the file you make to keep records and I will email the authors. Below are the 2 emails I sent to non-english authors recently. I will continue to add sample emails to this ticket. 
1. (contained a phet tips file instead of a real lesson)  (sorry no email recorded, this is just an example) 
Dear , I see that you shared an activity on the PhET website, but the uploaded file is not a lesson. It is a file that PhET wrote to help teachers. I have deleted your activity, but I would be happy to help you share a lesson. If you have any questions about what or how to share your ideas, contact me and I will help you.
Best wishes,  
Trish Loeblein
Patricia.Loeblein@colorado.edu
PhET K12 Specialist http://phet.colorado.edu/ 


2. (contained a resume) 'menorv@hotmail.com' 
 Dear santi menor,
The PhET teacher activities are meant to be helpful ideas for using the simulations. Posting your resume here is the wrong place. I have deleted your activity. 

Good luck in your job hunting, 
Trish Loeblein
Patricia.Loeblein@colorado.edu
PhET K12 Specialist http://phet.colorado.edu/

**Comment by patricialoeblein** [comment]
Please make the recording file a spreadsheet so we can easily sort. Let's call it "Deleted Activities". Column headings should be: Author name, email, language (we can put non-english if the specific language is not identifiable), reason to delete activity (corrupt file, incorrect file, inappropriate - with a specific reason so I can email), date, emailed date, response if received. 
thanks and call if you have questions 303.877.2119

**Comment by patricialoeblein** [comment]
I think we should also have a sheet be a place to document gold star activities. So now, I am thinking the title of this spreadsheet should be Teaching Activities Records. One sheet for Deleted Activities and one for Gold Stars. After you make the doc and share it with me, I will add columns for the Gold Stars, but I want to think about what we would document and include some other PhET resource people.

**Comment by ariel-phet** [comment]
@patricialoeblein - just a note I edited your comments above to remove email addresses and phone numbers. Since github is public we want to be careful about those things.

**Comment by patricialoeblein** [comment]
Thanks

**Comment by elisemorgan** [comment]
@patricialoeblein Do you want all Gold Star activities compiled or just the non-English?

**Comment by elisemorgan** [comment]
@patricialoeblein @ariel-phet I just need a little clarification. https://phet.colorado.edu/en/contributions/view/3944 This document isn't a lesson but seems to be instructions on how to use the sim. My impression is that this is the kind of thing we don't want, correct?

**Comment by ariel-phet** [comment]
@elisemorgan - it is true that such instructions are not ideal in terms of what we recommend for sim lessons, but such a contribution is not junk/spam. Basically, I think what we are looking for are uploads that clearly do not pertain to the sim (someone's resume, some sort of nonsense, etc). We are not looking to judge the quality of contribution as a teaching tool, just to make sure it is relevant to the sim and not junk or something nefarious.

So for instance, I think it is unlikely, but you could imagine someone being very sneaky and uploading something that looked relevant to the sim but had links to spam or such in the document. That would be an example of something we would want to take down. But in general, if the doc relates to the sim (even if cook book instructions on usage), we will want to leave it.

Does that clarify?

**Comment by patricialoeblein** [comment]
elise Ariel is right about not judging the lesson; I tired to do that when nonenglish ones first were added, but the translation tools available don' t get the science well enough to judge. I quit trying to read them a few years ago which caused the problem of the bad activities still being published. Once you make the sheet with old ones, I will keep it up to date. I get notified every Sat about new activities and I will start checking non-english ones again.

For the Gold Star sheet, I will be making it; you don't have to do anything other than have the name of the file sound inclusive for activity data. We are starting to get a few files and I think we should have just one. Steele has already identified Gold star lessons in another file for a different project; when he returns in the fall I will have him move those. In the mean time, I will be adding new Gold stars. Call if you have questions. I will send you an email with my #.

**Comment by elisemorgan** [comment]
@ariel-phet @patricialoeblein Great that clarifies a lot

**Comment by elisemorgan** [comment]
@patricialoeblein Here is the list of the documents I deleted https://docs.google.com/spreadsheets/d/1S9qWDRdaVRW3VqEqiGD82YfF57kIPKiJ6aBrNQczQQE/edit#gid=0 and I believe those are all the non-English junk

**Comment by patricialoeblein** [comment]
Thanks Elise, 
15 icky activities gone due to your diligence. I will write the authors.

**Comment by patricialoeblein** [comment]
I have been sending email that look like this
subject "Inappropriate PhET lesson deleted" 
Dear  , 
You had uploaded a file containing (reason) perhaps in error to the PhET  teacher resources. The sharing on the PhET site is meant for teachers to get ideas to use PhET simulations. Please feel free to share your ideas for using PhET.
sincerely,

**Comment by ariel-phet** [comment]
Looks like this issue can be closed.
