### ISSUE TITLE
Testing for Charges and fields dev version 13.

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#315]
Please check the performance of the electric field grid on chrome, firefox, ie and ipad.
Pay attention to any pixellation effects ( which will be present but we want to minimize it in as much as possible)

- [x] Chrome
- [x] Firefox
- [x] IE
- [x] iPad2

Here is the link 
http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.13/

**Comment by ariel-phet** [comment]
@phet-steele - this should be a fairly quick test (perhaps report frame rates when dragging a charge around)

@arouinfar - might be nice to do some testing while feeling under the weather

**Comment by arouinfar** [comment]
@ariel-phet @phet-steele I can test on Mac OSX 10.10.4 and 10.9.5 since I have access to those platforms at home.

**Comment by ariel-phet** [comment]
@arouinfar since dev testing, try 10.10.4 on FF and Chrome

**Comment by phet-steele** [comment]
Well first of all, the "Direction Only" box is broken and doesn't do anything (which I think is okay in this case since I believe performance is worse with it off).

These three browsers were performed on Windows 8.1 64-bit while moving around one charge:
Firefox 40.0: went up to 40 charges --> 60fps (with the occasional 61fps!)
Chrome 44.0.2403.155 m: went up to 40 charges --> 60fps (also saw some 61s)
IE 11.0.9600.17905: went up to 40 charges --> 60fps

iPad 2 iOS 8.3
Just two charges and moving one --> 18fps
Max charges and moving one --> 15fps

iPad 3 iOS 8.3: 
Just two charges and moving one --> 15fps
Max charges and moving one --> 10fps

In both the cases with an iPad, the sim didn't look or feel unusable, or even that bad at all with these low frames. Also, pixelation in general was not bad. The arrows are only slightly aliased at small angles around plus or minus 90, 0, and 180 degrees.

**Comment by ariel-phet** [comment]
@veillette see above for results of dev testing

**Comment by arouinfar** [comment]
Testing on Mac OSX 10.10.4 with latest Chrome and Firefox yielded similar results to the Windows testing reported by @phet-steele. The pixellation is noticeable compared to previous versions, but not severe (FF is a little worse than Chrome). I agree that it will probably go unnoticed by most.

**Comment by veillette** [comment]
I corrected the 'Direction Only" problem I introduced in this new dev version. It seems that we have solve the slowness problem https://github.com/phetsims/charges-and-fields/issues/59
and it doesn't seem to affect ipad2 performance too much (if at all).

Closing
