### ISSUE TITLE
Draft email to trusted translators to update profile

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#381]
@oliver-phet and @ariel-phet should draft an email to the trusted translators to have them update their profile in anticipation of us opening up HTML5 sims to translation (since profiles must be properly updated for us to make users a trusted translator)

**Comment by oliver-phet** [comment]
Dear [translator's name],
We are excited to announce that very soon a new translation utility for our HTML5 sims will be available!

We have made a simple web interface for translating our HTML5 sims, and we would like to invite you to begin translating as we enable translatability in our HTML5 sims.

In order to grant you access to the new utility, we need to ensure your PhET website profile has been updated. Please visit http://phet.colorado.edu/ and Sign In. You will then be prompted to update your profile.

Once you have updated your profile, please send an email to phethelp@colorado.edu with your PhET website login email so that we will add access to your account.

**Comment by ariel-phet** [comment]
Dear [translator's name],
We are excited to announce that very soon a new translation utility for our HTML5 sims will be available! This new utility is a simple web interface for translating our HTML5 sims, and at first, we will only be granting access to one translator per language/locale.

As a first step, we need to ensure your PhET website profile has been updated. 
1. Please visit http://phet.colorado.edu/ and Sign In. 
2. If you have not updated your profile, you will then be prompted to update.
3. Once you have updated your profile, please send an email to phethelp@colorado.edu with your PhET website login email so that we can grant you access to the translation utility.

Once we have given you access we will send a follow up email with instructions on how to access and use the new utility. 

Please note, that only one or two sims will be available to translate at first, as making our HTML5 sims translatable requires each of them to be updated. However, over the next several months we will be working hard to perform these updates, and more sims will become available regularly.

**Comment by ariel-phet** [comment]
@oliver-phet what do you think about the above edits?

**Comment by oliver-phet** [comment]
That looks good. Ready to be sent to trusted translators?

**Comment by ariel-phet** [comment]
yes, go ahead and send, and then close the issue, thanks!
