### ISSUE TITLE
RC Test: Molecules and Light 1.1.0-rc.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#385]
New release candidate for Molecules and Light is deployed to spot and ready for testing.

**Test Matrix:** https://docs.google.com/spreadsheets/d/1SIuHF5V4TPR-H2FHugvL52cB6MvQ60gYgg-W-88A6mg/edit#gid=553184252

**Link to RC version:** http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.4/molecules-and-light_en.html						

**Link to iframe:** http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.4/molecules-and-light_en-iframe.html

Version 1.1.0 was already tested in other release candidates so we just need to spot check this RC and make sure that everything looks good after patches from chipper and scenery for build server and https://github.com/phetsims/scenery/issues/464.

**Comment by ariel-phet** [comment]
**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over @pixelzoom's revamped code review checklist, decide if code review should be redone
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md 
- [ ] Address RC issues and publish
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now

**QA**
- [ ] stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingThatDoubleDidNotExpose
- [ ] RTL language test
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process

**Comment by ariel-phet** [comment]
@jessegreenberg please look over the above list, and lets make sure everything is check off on the dev side before RC testing commences. If something needs attention, please address, publish a new version and edit the links above as necessary.

**Comment by jessegreenberg** [comment]
We need a new RC for MAL with stable SHAS and a fix for drag performance after the iframe issue.  Closing this, and moving to the next RC.  Redeploy checklist will be moved to the new issue as well. Closing.
