### ISSUE TITLE
Coin artwork

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#401]
I'm making this issue so it is on your radar @mariahmaephet . I am working on a sim that uses coins, and we do not want to use US coins but rather some arbitrary-looking coins. I have compiled some images of coins with different types of metals, different shapes, and even various images (I'm not sure yet if we want images or not). When you have some time I'd like to meet up to discuss some ideas I have and show you the big picture of the sim.

**Comment by mariahmaephet** [comment]
@amanda-phet Alright! I'm available the next 3 days any time before 1pm

**Comment by mariahmaephet** [comment]
@amanda-phet these are easy enough to do without a tablet. I'll decorate them more later this week but for now we can figure out their general size and color.

I was thinking since you said each row was similar that that could be what decided the color--so bronze silver or gold for the different variables. 
<img width="551" alt="screen shot 2015-11-03 at 9 54 48 am" src="https://cloud.githubusercontent.com/assets/11527557/10914996/09e46fb8-8212-11e5-9d1d-0dd0e64d6d17.png">
<img width="249" alt="screen shot 2015-11-03 at 9 58 51 am" src="https://cloud.githubusercontent.com/assets/11527557/10914995/09e05518-8212-11e5-92be-e2e5f8d8941b.png">

**Comment by mariahmaephet** [comment]
<img width="616" alt="screen shot 2015-11-06 at 9 59 20 am" src="https://cloud.githubusercontent.com/assets/11527557/11002949/1dd41408-846d-11e5-9f47-20bcd40d02ad.png">

**Comment by ariel-phet** [comment]
I definitely like having different shapes (such as the 6 sided, and the one with a hole in it, to make them easily distinguishable. The drawings above look like they have just a bit too much perspective to my eye, I think you only need a hint of the 3D-ness (since coins are pretty flat.

**Comment by mariahmaephet** [comment]
Is this better? @amanda-phet @ariel-phet 

<img width="608" alt="screen shot 2015-11-24 at 11 36 09 am" src="https://cloud.githubusercontent.com/assets/11527557/11376733/995386be-929f-11e5-909b-4e5d57fdc2ac.png">

**Comment by ariel-phet** [comment]
As I said in our meeting, I think the perspective is looking better. Although I love the designs on the coins (like PhET girl!) we might have to see how they work in context and make sure they are not too busy.

**Comment by amanda-phet** [comment]
These look great to me! I agree that we will need to see how they work in context and then I may have more tweaks for you.

**Comment by amanda-phet** [comment]
@mariahmaephet can you drop the .ai file in to drive so I can play with the coins in context?

**Comment by jbphet** [comment]
I'm now integrating these images into the simulation, and for the most part they are working great.  However, one minor adjustment is needed: The the hole in the center of the one coin that has such a hole should be transparent, otherwise it looks a little weird.  Here's a portion of a screenshot to illustrate the problem:

![ex-ex-coin-hole](https://cloud.githubusercontent.com/assets/3082831/12157491/557857d2-b48f-11e5-8d84-202e1608815d.png)

**Comment by amanda-phet** [comment]
I took care of this fix and will email @jbphet an updated .ai file.

**Comment by amanda-phet** [comment]
Since we have the artwork for this task I'll go ahead and close this issue.
