### ISSUE TITLE
Investigate Chrome web store

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#403]
@arnabp can you look into the Chrome web store again? What would it take to put an HTML5 sim on the store? All of our HTML5 sims?

Also, @aadish mentioned Appcache manifest - investigate bookmarking html5 sim: http://www.html5rocks.com/en/tutorials/appcache/beginner/

**Comment by oliver-phet** [comment]
@mattpen Is going to investigate... also look into packaging a Flash sim to investigate offline usage.

**Comment by mattpen** [comment]
I created an account to upload apps and have packaged an HTML5 app that is ready to test (pending payment of the fee).  Publishing a flash app should be fairly simple since we already have them packaged for download.

There are a few items to consider.

1. Publishing requires a google account, which shows up on the store page under "offered by".  I created a Google account called phetdev, I'm not sure if we already have one we can use.
1. There is a one time $5 fee to publish apps to the web store.
2. Do we want to publish to Google Play for Education? http://developer.android.com/distribute/googleplay/edu/start.html
3. There is a requirement for a 16x16 and 128x128 icons for each app. There are options for including promo images of larger sizes and a YouTube video.
These were the only icons I could find of this size: https://phet.colorado.edu/images/support/science4us-small.png
http://phet.colorado.edu/newsletters/2015-spring/phet-icon.png
4. There are options for Internationalization of the promo materials. See https://developer.chrome.com/extensions/i18n for more details.

As far as the developer side goes, this is fairly easy.  We just take a packaged app, add a manifest file and icons, and compress it and upload it.

**Comment by oliver-phet** [comment]
@mattpen We already have an account setup. We can talk about it at meetings today.

**Comment by mattpen** [comment]
@oliver-phet I've run into a significant obstacle using the offline html5 packages from the website.  The javascript needs to be in a separate file, it will not run as a packaged app in Chrome if the js is inline.  Do you know which developer packages the HTML5 apps?

**Comment by oliver-phet** [comment]
No idea. Maybe @ariel-phet knows. I thought it was a semi-automated process.

**Comment by oliver-phet** [comment]
Just ran into Ariel. Talk to @jonathanolson about the build process.

**Comment by samreid** [comment]
Another step to manage if publishing on the Chrome web store: we would want to gather and integrate usage statistics (if possible).

**Comment by samreid** [comment]
> Publishing requires a google account, which shows up on the store page under "offered by".

Can you show a picture of what this looks like to the end users?  Perhaps we would want to name this "phet" or "PhET" or "PhET Interactive Simulations" or "phet-interactive-simulations" or "phetsims", depending on the context.

**Comment by samreid** [comment]
> I've run into a significant obstacle using the offline html5 packages from the website. 

There are a few ideas in this thread about how to extract script tags from an HTML document:
http://stackoverflow.com/questions/6659351/removing-all-script-tags-from-html-with-js-regular-expression

We have two main options:
(1) write a script that takes a built (single) HTML file and extracts the script tags to a single JS file
(2) update the build process so that the single HTML + single JS are created initially

It is unclear which would be easiest in the long run, but if it were me I would at least spend a little time looking into (1) to see what's possible/easy and how robust that strategy seems in practice.

**Comment by jonathanolson** [comment]
Working with @mattpen, it was easy to patch the build process to output chrome-web-store-compatible directories (one HTML, multiple JS), in https://github.com/phetsims/chipper/commit/977e35cdd69b6be5bbfa4cc3a977aa5264b50bd3 (6 hours ago), but it doesn't follow (1) or (2) since it was easier to have multiple scripts. Presumably it would need changes and documentation before merging in (we probably don't want to build the bundles every time, OR want to change chipper/build-server to actually create/submit the bundle + manifest).

It's on the Thursday agenda to discuss items related to this, including the first two items below:
1. Constraints for being compatible. No eval/Function( ... ) usage is acceptable, so numeric.js is dead in the water for this (2 sims use it, and it looks difficult to patch since a ton of code is auto-generated effectively). This may also prohibit us from using other libraries that use those features in the future.
2. Changes to the build process, and integration with the build server, rosetta, automated tools, and deployment.
3. Technical constraints for Flash sims. Chrome by default doesn't auto-load Flash, and there was no obvious way to right-click to load (as it brought up a different context menu). This may require users to enable auto-play of Flash content to run Flash sims packaged this way.
4. Google Analytics integration.

**Comment by samreid** [comment]
> but it doesn't follow (1) or (2) since it was easier to have multiple scripts. 

Multi-scripts sounds good, no problem.  Looking forward to discussing the other points in the future.

**Comment by mattpen** [comment]
>Can you show a picture of what this looks like to the end users? 
>>Publishing requires a google account, which shows up on the store page under "offered by"

Oliver has already setup one of the phet gmail accounts (phethelp@gmail.com) to be able to publish to the webstore and he verified our URL and such.  Its showing up as "offered by phet.colorado.edu".

![image](https://cloud.githubusercontent.com/assets/11747676/11659326/ef2a2c60-9d84-11e5-944d-5d06e4c3b391.png)

**Comment by mattpen** [comment]
It looks like there is a separate JavaScript library for integrating GA into Chrome packaged apps.  https://github.com/GoogleChrome/chrome-platform-analytics/wiki
We'll need to look into adapting the current script to work with this API.

**Comment by oliver-phet** [comment]
@mattpen Please publish the Molarity/Density combo for testing on a Chromebook to see if we can get the Flash sim to run. Do you have a URL with info on enabling Flash?

**Comment by mattpen** [comment]
How to enable flash to always run: https://helpx.adobe.com/flash-player/kb/enabling-flash-player-chrome.html

**Comment by mattpen** [comment]
@oliver-phet The link will be available from the [developer dashboard](https://chrome.google.com/webstore/developer/dashboard?authuser=2) soon.  You will need to be logged into google as phethelp@gmail.com.

**Comment by oliver-phet** [comment]
@brroberts1231 @BryceAG Take a look at this and report.

**Comment by brroberts1231** [comment]
Successfully ran in offline mode. The instructions to enable flash to always run I think are simple enough. I added the Density and Phet Package apps and they both worked when I turned off the wifi on the chromebook. The energy skate park basics would open up offline, but got stuck on the loading screen whether I was online or offline.

**Comment by brroberts1231** [comment]
The apps work on both Vygotsky and Chadwick.
It also appears that they can work even if the check box for "always allowed to run" is not checked, just as long as flash is enabled.

**Comment by mattpen** [comment]
There exists an [API for publishing and updating apps](https://developer.chrome.com/webstore/api_index)

It appears there will still be some manual work involved.  
* The initial setup of the page for each sim will need to have the description, screenshots, category, etc. set manually.  This cannot be set with an API or configuration file.
* It appears that human interaction is also required to use the API.  A person will need to download an authorization code which will be valid for 40 minutes at a time.  This will need to be added to the checklist for deploying a sim if we want the chrome webstore to be synchronized with the website.

I haven't done any testing yet, I plan to work on that next week.

**Comment by mattpen** [comment]
@jonathanolson @samreid - I think I've found a work-around for allowing inline js in the chrome apps.  We would just need to package them in a [sandbox](https://developer.chrome.com/apps/app_external#sandboxing).  This would limit our ability to use any of the Chrome App API's, but that doesn't create any problems with the existing sims.  I was able to install and test Energy Skate Park Basics as a Chrome App locally without removing any numeric code.  

It appears promising that we can even reuse the GA code already packaged in the HTML5 apps, but I haven't tested it yet.

**Comment by samreid** [comment]
@mattpen that sounds promising, especially if it helps with analytics.  We may still want to abandon numeric.js and other eval/based approaches for future, but sandboxing seems straightforward for now and worth further investigation.

**Comment by mattpen** [comment]
@oliver-phet - Is translatability a priority for this project?

**Comment by oliver-phet** [comment]
Not a priority right now. If there is a lot of demand for our sims via the Chrome web store in the future, we can investigate then.

**Comment by ariel-phet** [comment]
At the moment, the current plan would be to make an android app similar to what we have done as an iPad app that bundles the sims, and allows offline use. Google is planning on unifying the google play store for both Chromebooks and android, so ideally this would be the route we take. Closing.
