### ISSUE TITLE
Incomplete types are added to namespace

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#433]
From #378 @pixelzoom said:

> our agreed-upon convention [is] putting the register call immediately after the constructor.

Thinking about this a bit further, consider this simplified example type declaration:

```js
function MyType(){ ... }
namespace.register('MyType',MyType);
return inherit(SuperType,MyType);
```

It seems problematic to add something to the namespace before it can be used.  And in this case, the MyType constructor should not be called until after the inherit method has completed.  Therefore, in cases like this we should add to the namespace after the inherit call is completed.

We decided to put the register call right after the function declaration in part from looking at beers-law-lab Solute.js but this is a special case because it has no supertype.

It may be acceptable to add broken things to the namespace if we can guarantee they will never be used while broken.  But thinking about phet-io patterns, which it is conceivable *may* be employed here, we may have callbacks when an item get registered with a namespace, and call on it immediately.  For instance, a rule like `as soon as the MyType class is declared, create an instance of it` generally wouldn't work with the ordering specified above.

Linking back to #431, which is where I thought of this potential problem.  Let's discuss it with @aaronsamuel137 @jessegreenberg @jbphet @pixelzoom and @jonathanolson and I'll mark it for developer meeting in case there is no consensus by then.

**Comment by jonathanolson** [comment]
If this is something that we'd need, I'd argue that after the inherit (or even at the bottom of the file) is insufficient. Just because we've loaded the entire file doesn't mean it's in a state where you can create instances and do whatever. For example:
1. After Node is fully set up in Node.js, new Node().toCanvasNodeSynchronous() would try to create a Scenery Image (which hasn't been loaded yet, since it depends on Node).
2. Similarly with Vector2's toVector3().
3. instanceof usage where it relies on the referenced type to be loaded.
4. Scenery's Text needs additional elements added to the DOM so that it can detect text bounds properly. This is currently done after the inherit call, so putting registrations immediately after the registration call would not support immediate creation for Text.
5. Similarly, most types that mix-in Poolable will do so after the inherit.
6. Namespaces themselves (when created, particularly if a pattern is used to use sub-Namespaces) won't be fully complete on creation, as they haven't had anything registered yet.

Maybe for phet-io it's appropriate to wait until the start of the main script, where everything has loaded, but the sim hasn't been started?

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> Maybe for phet-io it's appropriate to wait until the start of the main script, where everything has loaded, but the sim hasn't been started?

+1

**Comment by samreid** [comment]
In this case, waiting for the sim to launch before accessing any of the namespaced objects makes sense.  For phet-io instrumented instances, there is a similar question: should we be able to deal with objects right when they are created or only after the sim has started up.  I originally thought of applying the same logic here, but it doesn't address the case of instances that are created *after* the sim was initialized.  However, loading static code is different than dealing with dynamically created instances, so I think this separation is OK.

**Comment by ariel-phet** [comment]
Tagging for dev meeting....can this issue be closed?

**Comment by pixelzoom** [comment]
Here's our current pattern for namespace registration:

```js
function Subtype(...) { 
  Supertype.call( this,...);
  ...
}

namespace.register( 'Subtype', Subtype );

return inherit( Supertype, Subtype );
```

If it's important to register only "complete" types, then change our pattern to this:

```js
function Subtype(...) { 
  Supertype.call( this,...);
  ...
}

inherit( Supertype, Subtype );

namespace.register( 'Subtype', Subtype );

return Subtype;
```

**Comment by samreid** [comment]
The approach in the preceding comment has been working acceptably well for phet-io.  We haven't identified any practical cases like `as soon as the MyType class is declared, create an instance of it`, so perhaps our plan is sufficient for the foreseeable future.

**Comment by jonathanolson** [comment]
> If it's important to register only "complete" types

My comment https://github.com/phetsims/tasks/issues/433#issuecomment-156787995 notes that registering at the end of the module still isn't enough to only register complete types.

**Comment by pixelzoom** [comment]
Sounds like the answer to @ariel-phet's question is: Yes, this issue can be closed, because what we're currently doing is working.

**Comment by pixelzoom** [comment]
2/18/16 dev meeting, yes ok to close.
