### ISSUE TITLE
RC Test for Molecule Shapes 1.1.2-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#477]
Testing Matrix: https://docs.google.com/spreadsheets/d/1wfA1SVvOKK-d26ozNNeGDuuq5OtUpInGcEkfK_Eqvgg/edit#gid=334453563

Direct link to HTML: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.2-rc.1/molecule-shapes_en.html

This was published out of master, so presumably it will need a full re-test.

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [ ] Address RC issues

**QA**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Perform RC testing
 - [x] Reference issues to RC test task

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by jonathanolson** [comment]
I'll have the Molecule Shapes: Basics test up soon. It crashed the build-server when I tried to use the new way, so it's a bit delayed.

**Comment by ariel-phet** [comment]
**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] Perform RC testing

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
@jonathanolson can you please verify that the remaining developer steps above are complete before I assign this for QA?

**Comment by jonathanolson** [comment]
Complete except for "Address RC issues" which presumably happens later.

**Comment by ariel-phet** [comment]
@elisemorgan @brroberts1231 @orejolaphet @BryceAG @bryo5363 @phet-steele please make this the top testing priority

**Comment by phet-steele** [comment]
@jonathanolson testing matrix done.

**Comment by phet-steele** [comment]
@jonathanolson I'm assuming this can be closed?

**Comment by ariel-phet** [comment]
yes this can be close now
