### ISSUE TITLE
RC Test for Molecule Shapes: Basics: 1.1.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#478]
Testing Matrix: https://docs.google.com/spreadsheets/d/1pfJglrdMScIyruOXQilQiNse91tGhafQKLouOJISSMY/edit#gid=1989446480

Direct link to HTML: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.0-rc.2/molecule-shapes-basics_en.html

This was published out of master, so presumably it will need a full re-test.

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [ ] Address RC issues

**QA**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Perform RC testing
 - [x] Reference issues to RC test task

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] Perform RC testing

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
@jonathanolson please verify that the remaining developer steps above are completed before I assign for QA

**Comment by jonathanolson** [comment]
Complete except for "Address RC issues" which presumably happens later.

**Comment by ariel-phet** [comment]
@elisemorgan @brroberts1231 @orejolaphet @BryceAG @bryo5363 @phet-steele please make this a top testing priority along with molecule shapes

**Comment by phet-steele** [comment]
@jonathanolson testing matrix complete
