### ISSUE TITLE
Charging "station" for QA devices

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#492]
@phet-steele had suggested that we come up with a plan for a charging station for our test devices. This seems like a good idea, and might be especially nice to set up once we have moved offices.

@phet-steele please note a bit more specifically what you are proposing in this issue (for instance maybe we just need a nice wall mounted power strip and a custom shelf or such).

Edit: if you had some specific things in mind maybe have links to them on amazon?

**Comment by phet-steele** [comment]
@ariel-phet This is what I was imagining:
http://www.amazon.com/Luxor-Charging-Tablets-chromebooks-Horizontal/dp/B013RMI32Y/ref=sr_1_30?ie=UTF8&qid=1454532902&sr=8-30&keywords=wall+mounted+charging+station

I'm not saying buy this, but it's the closest representation of what I had in my head (besides, according to the single, 1-star review, it isn't even big enough for a chromebook let alone laptop). I've done the math also, and the 16 outlets this happens to have is exactly the bare minimum we need.

A more reasonable but much more crude solution would be this:
http://www.amazon.com/FlePow-6-Outlet-Protector-Charging-Retractable/dp/B01821W47A/ref=sr_1_11?ie=UTF8&qid=1454532262&sr=8-11&keywords=usb+and+outlet+power+strip

This would be much easier. However, the reason I liked the first idea is that it would eliminate the cord mess, but this power strip option would most likely be messy. Also, again with the math, we would need two of these strips to be able to charge everything.

In case you wanted to know the math:

Devices needing an outlet: 9
Devices that could be USB or outlet: 7

This was only the most essential devices, not taking into account the rare use tablets or devices with a different home (ie. Copernicus or Mendeleev).

**Comment by arnabp** [comment]
I checked online for some commercial solutions to this, and it should be noted that they all range from $300 to $600 depending on size and construction. [Examples](http://www.globalindustrial.com/g/office/computer-furniture/laptop-storage-charging/luxor-laptop-storage-charging-cart).

The middle ground solution to buying one of these and sticking a surge protector on a table with a bunch of wires everywhere is to simply jerry rig our own cabinet. We'd still use the surge protector, but I'm sure we could find an adequate cabinet to use, drill a few holes in, and wire everything so that most of the wiring is hidden and everything is still neatly laid out.

**Comment by phet-steele** [comment]
@ariel-phet we currently have a working solution in the office, come check it out! If this suits me well, I'll close this.

**Comment by ariel-phet** [comment]
@phet-steele is this the rolling charging station?

**Comment by phet-steele** [comment]
Indeed.

**Comment by phet-steele** [comment]
🎉
