### ISSUE TITLE
Testing "Puffin Academy" Browser on iPad for Flash sims

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#507]
The "Puffin Academy" app on iPad was recommended on twitter as a way to run all of our flash sims. I tried this a bit and it seemed to be performing well. We should install the app on one of our iPad2's running iOS 9+ and test all of our flash sims.

Mainly, we just want to test for performance, and see how it compares to desktop. Obviously report if something looks obviously buggy, but from what I saw, things look pretty smooth. In addition, this is a cloud based service, so presumably they are running flash on their servers, and then serving the content through the browser, so nothing should be wrong with the sim from a bug point of view.

We tried this solution in the past, and it was unsatisfactory, but perhaps it has vastly improved.

- [x] Blackbody Spectrum
- [x] Buoyancy
- [x] Calculus Grapher
- [x] Charges and Fields
- [x] Collision Lab
- [x] Curve Fitting
- [x] Density
- [ ] Equation Grapher
- [ ] Estimation
- [ ] Geometric Optics
- [ ] Lunar Lander
- [ ] Masses and Springs
- [ ] My Solar System
- [ ] Normal Modes
- [ ] Pendulum Lab
- [ ] Plinko Probability
- [ ] Projectile Motion
- [ ] Radiating Charge
- [ ] Resonance
- [ ] Stern-Gerlach Experiment
- [ ] Vector addition

**Comment by ariel-phet** [comment]
Assigning to @phet-steele - not a major priority, but would be good to test and should be fairly quick. If everything looks good we will probably put a recommendation on our "by device" iPad category page and such.

**Comment by ariel-phet** [comment]
@phet-steele looks like you have tested several sims....thoughts so far?

**Comment by phet-steele** [comment]
@ariel-phet the check boxes have actually been @BryceAG (who may have some thoughts?), but you still aren't wrong since I have been testing it now and again! Performance is all over the place, sims that (I'm assuming) have heavy data transfer are really slow, like Normal Modes, Radiating Charge, My Solar System, etc.., while other sims run adequately well, like Density, Curve Fitting, Pendulum Lab, etc... There were a few surprisingly good ones, like Resonance and Masses and Springs.

The biggest reason why I'm hesitant to say yea or neigh on this is that none of these sims have been built to run well with touch inputs. ALL of the sims with sliders or radio buttons are incredibly frustrating to use, like I want to throw the iPad across the room type of frustrating. You have to be so incredibly accurate with your touches for any feedback, and dragging sliders is very sluggish.

So those are my thoughts so far; I'm still on the fence about saying this good or not. Some sims look great for this, while most are basically unusable.

Another note, Lunar Lander is a special frustrating use case. I have to use the app's "Gamepad" UI to control the lander. The gamepad felt slightly unresponsive while also covering up the reset button in the sim.

**Comment by ariel-phet** [comment]
OK, thanks for the report @phet-steele , I think we can end testing there. I think this is something we will keep in our back pocket to tell people if they are "desperate" to use a flash sim on an ipad but not advertise anywhere on the website.
