### ISSUE TITLE
Performance tests for overflow fix

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#529]
For testing https://github.com/phetsims/phet-io/issues/341, I want to make sure that this change won't adversely affect performance.

Can the two sims (in both the "fixed" and normal) configurations under http://www.colorado.edu/physics/phet/dev/olsonjb/no-overflow/ be tested on a range of platforms, to see if performance is significantly affected?

Ideally, try to put things off-screen (meters, pendulums, etc.) to see if that triggers losses. Please note any performance losses beyond the "normal" version, and details if necessary on how to trigger the performance loss.

Presumably no need to create performance-specific issues, I'll handle anything that comes up in https://github.com/phetsims/phet-io/issues/341.

Recommended platforms for testing:
- [x] iPad 2
- [x] iPad 3
- [x] Safari 9 (any OS X)
- [x] Firefox (Win)
- [x] Firefox (Mac)
- [x] Chrome (Win)
- [x] Chrome (Mac)
- [x] IE11
- [x] Edge

> Please make a task, assign it to @phet-steele and let him know he can delegate as he sees fit.

Delegate as you see fit!

**Comment by brroberts1231** [comment]
Link to phet-io#341 gives 404 error, so I will leave what I find in here.

**Comment by jonathanolson** [comment]
@ariel-phet, presumably QA should have some access to phet-io and hidden repositories?

**Comment by brroberts1231** [comment]
Between the two Beer's law lab versions, I don't see any major performance issues as of yet, but I did find that if given the same inputs for wavelength and concentration, the two versions can sometimes give different transmittances (probably due to differences in rounding error.) 
This seems to mostly happen at low concentration values.

Original  version: 
![screen shot 2016-03-02 at 12 35 00 pm](https://cloud.githubusercontent.com/assets/11947677/13472695/45f0181c-e073-11e5-9335-669c43f21617.png)

Fixed version:
![screen shot 2016-03-02 at 12 36 08 pm](https://cloud.githubusercontent.com/assets/11947677/13472723/5fedf306-e073-11e5-9a05-3fb1c1b30a37.png)

I'm testing on Mac chrome currently

**Comment by brroberts1231** [comment]
Never mind about this last issue, I think that dragging the slider can place it on fractions of mM between the whole numbers you see, slightly altering the calculation. If I change the concentration by only using the arrows, the transmittances will be the same every time.

**Comment by ariel-phet** [comment]
Yes, they should have access, I have added QA team to the repo.

**Comment by phet-steele** [comment]
@jonathanolson platforms have been tested. I saw no discernible difference between the two.

**Comment by jonathanolson** [comment]
Thanks!
