### ISSUE TITLE
Design of Keyboard Info button and popup

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#619]
To start publishing sims with keyboard navigation, we need a visual way to cue users of what keys do what. This will require an onscreen button, and a popup window that lays out visually the usable keys and their actions.

Taliesin has done some work getting this started, but it will ultimately need to be iterated on and discussed within the PhET team as it will have a (small) visual impact on each sim. 

Could one of the designers work with Taliesin on mockups, and helping discuss with the team?

**Comment by ariel-phet** [comment]
@arouinfar I think you would be a good fit for this work.

We should first decide where such a button should live (most likely will need to be in the navbar) If that is the case, we should move this issue over to Joist eventually.

@arouinfar please get in touch with Taliesin to see what she has thus far. Feel free to wrap me into discussions/iterations.

**Comment by emily-phet** [comment]
@arouinfar - I can also talk with you about the general idea tomorrow.

**Comment by arouinfar** [comment]
Sounds good @emily-phet!

**Comment by arouinfar** [comment]
I Skyped with @emily-phet this afternoon, and I've reached out to @terracoda to schedule a follow-up chat sometime next week. 

@ariel-phet I'll most likely want to discuss this with you once I've talked to Taliesin.

**Comment by arouinfar** [comment]
Thanks @terracoda! I've emailed you a Zoom link.

**Comment by emily-phet** [comment]
@arouinfar - did you have a chance to create any mockups? If so, could you pass these along to me, Taliesin, and Jesse as soon as possible? We can discuss further in a design meeting, but I don't think Taliesin will be able to join this Thursday so it would be good to get the conversation started in advance.

**Comment by arouinfar** [comment]
@emily-phet I'll have some mockups to share later this afternoon.

**Comment by emily-phet** [comment]
@arouinfar - great, thanks!

**Comment by arouinfar** [comment]
Here's a link to the design doc:
https://docs.google.com/document/d/1XE0_T6YCe9wBkqlf82GlyyNNfXy-bipVLRSojQayaZ8/edit

Last meeting we came up with a new general layout for the navbar along these lines:
![image](https://cloud.githubusercontent.com/assets/8419308/20151350/136a3790-a677-11e6-9085-9f9ab775d08d.png)

The design for the icon itself has yet to be determined. I have a few more options to mockup, which I can work on this afternoon.

There is also still work to be done on the dialog. @terracoda has created some preliminary mockups of a modal dialog.
<img width="512" alt="screen shot 2016-11-09 at 12 24 19 pm" src="https://cloud.githubusercontent.com/assets/8419308/20151481/896068b6-a677-11e6-8fa9-799da4e68d39.png">
<img width="511" alt="screen shot 2016-11-09 at 12 24 10 pm" src="https://cloud.githubusercontent.com/assets/8419308/20151480/895cfb22-a677-11e6-91b0-090096ca3d5b.png">

**Comment by arouinfar** [comment]
@emily-phet @terracoda @ariel-phet here are some updated icon options
<img width="1032" alt="screen shot 2016-11-09 at 1 06 33 pm" src="https://cloud.githubusercontent.com/assets/8419308/20152881/6213962e-a67d-11e6-9782-27b84a4089ed.png">

**Comment by ariel-phet** [comment]
At this point, from our earlier discussions I would be leaning towards (2) or (5)

For option (2) I think that signals "navigation" and moving around with the keyboard well

For option (5) I think that signals "keyboard" well and with the cord is not as easily confused with bringing up a keyboard.

I think either of these two could work and both look pretty good. I have a slight preference for the (5) keyboard, as it seems a bit more "airy" and less heavy and seems to match the general style of the navbar well.

**Comment by terracoda** [comment]
I prefer 5 as it is more general. We can't actually use the arrow keys for interaction in BASE, and we have more hot keys than just the directional WASD keys. For some sims arrow keys may not be relevant.

As for the PhET dot dot dot part have you thought about adding in the word "menu" visually to emphasize that the dots indicate a menu?

**Comment by terracoda** [comment]
Also, please keep in mind that the dialog samples were very early content. The interactions have changed and the content has changed as well. The new content is in #195.

**Comment by emily-phet** [comment]
@terracoda - are you sure you referenced the correct issue above? 
Also, good suggestion for the dot dot dot menu, though it's current design has been chosen to make sure the menu button takes up as little horizontal space as possible (note: the touch area for the menu includes the PhET logo next to it - so clicking/touching either or both opens the menu).

**Comment by emily-phet** [comment]
For the button icon, I actually have a preference for (1) above...but to be honest I'd be plenty happy with (5). 
Why don't we go with (5), since that seems to have a majority vote (from this discussion and from design meetings). 

@arouinfar @kathy-phet @ariel-phet - are their any changes to the general look and feel of the keyboard icon in (5) above that is needed to make it consistent with PhET icons in general? I think @arouinfar pulled this from somewhere just for a quick mockup, it may need to be customized.

**Comment by terracoda** [comment]
@emily-phet, correct that was the wrong related issue number. There are two related issues to this discussion:
- https://github.com/phetsims/balloons-and-static-electricity/issues/141, and 
- the closed issue https://github.com/phetsims/balloons-and-static-electricity/issues/195

The closed BASE issue number 195 has the latest content.

@arouinfar @kathy-phet @ariel-phet, if customization of the icon is possible, we might want to consider combining the keyboard and a question mark.

**Comment by ariel-phet** [comment]
@terracoda the "dot dot dot" icon is a pretty common web standard (google chrome uses this icon, and so do some web pages/mobile browsers). Adding the word menu would be problematic, and ideally we want to keep this purely iconic.

**Comment by ariel-phet** [comment]
@terracoda that combination is possible, we can certainly have our graphic artist take a stab at some treatments.

**Comment by terracoda** [comment]
@emily-phet, as for the PhET dot dot dot part, if one turns the word menu vertically, one almost has the same effect as the dot dot dot. 

There were at least 2 talks about the usability of hamburger menus at UXPA Boston in May 2015. It's possible users have just gotten used to these new menu icons (dots and lines), but at that time, usability and understandability was not good. One suggested solution was to actually use the word "menu" or combine the word with the icon.

A trending design practice is not a "web standard" :) The research presented at UXPA was users didn't know what it was. But as I mentioned already, it's possible people are getting used to it. It's been a year and half since that research was presented.

**Comment by ariel-phet** [comment]
@terracoda - vertical would extremely problematic for our project, you have to remember that any word we use in PhET sims needs to be internationalizable and the word "menu" could get very long in other languages. 

In general, we tend towards icons for just this reason, especially where long words could cause layout problems. I completely see your point, but this seems like one of those cases where we may need to take a hit on initial understandability

**Comment by terracoda** [comment]
@ariel-phet, very good point on internationalization.

**Comment by arouinfar** [comment]
The changes to the navbar are being discussed in https://github.com/phetsims/joist/issues/374, and  one instance of the popup is being discussed in https://github.com/phetsims/john-travoltage/issues/127.

I believe the only outstanding item of discussion relevant to this issue is the appearance of the keyboard icon itself. The general consensus is that option 5 from https://github.com/phetsims/tasks/issues/619#issuecomment-259512960 is preferable for these reasons
* The icon is general and doesn't rely on any specific key, so it works for any sim
* It signals "keyboard" and the cord helps break the expectation that a keyboard will open
* The icon appearance is airy, and fits in with the style of the navbar

That said, the keyboard itself will need to be tweaked slightly because it was a random image from Google. I've created this alternative, which is a modified version of the keyboard icon from font awesome. 

![screen shot 2016-12-12 at 1 00 52 pm](https://cloud.githubusercontent.com/assets/8419308/21114665/11fdf802-c06b-11e6-9c75-94463ef01885.png)

Here's the icon in a worst-case scenario navbar. The top icon is the one from Google images, and the bottom icon is the modified font awesome icon.
![screen shot 2016-12-12 at 1 00 42 pm](https://cloud.githubusercontent.com/assets/8419308/21114660/0b42215a-c06b-11e6-8d21-6d312392f9e1.png)

What do you think @ariel-phet @emily-phet @terracoda? If we're all happy with this version, I will send it off to @jessegreenberg to implement in https://github.com/phetsims/joist/issues/374.

**Comment by emily-phet** [comment]
@arouinfar Looks good to me - I think the more blocky keys help to signal "physical keyboard."

**Comment by arouinfar** [comment]
Thanks @emily-phet, I agree!

**Comment by arouinfar** [comment]
Spoke with @ariel-phet, and it looks like we can go with the modified font awesome icon for now. I've emailed the asset files to @jessegreenberg. Closing.

**Comment by terracoda** [comment]
@arouinfar, sorry for the late reply, but I agree and prefer the modified font awesome icon as well.
