### ISSUE TITLE
dev testing on Pendulum-lab version 1.0.0-dev.10

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#631]
We have resolved many issues on the pendulum lab. We would like to get some attention from the QA team. 

Link to dev version:
http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.10/pendulum-lab_en.html

Dev Test Platforms:

- [ ] iPad 2 iOS 9.3.1]
- [ ] Win Chrome

Please close any issues that have been correctly addressed. 
Please create separate issue for any problems that you find.

Assigning to @ariel-phet

**Comment by ariel-phet** [comment]
@veillette assigning back to you for the moment.

There are several important changes from dev.9 that do not seem to have made it into dev.10. Most notably in dev.9 you will notice that the way the mass scales is set so the shortest length and largest mass is below the pivot point as shown below. The ruler is also 1 m, instead of 2 meters in dev. 9.

Perhaps we should discuss on skype? I would like those modifications included before we dev test. Otherwise looking quite good!

![capture](https://cloud.githubusercontent.com/assets/4051174/16439872/a50e5102-3d79-11e6-8bfd-7a24b3ee8e6d.PNG)

**Comment by veillette** [comment]
Our team had discussion over Skype with @ariel-phet . We will resissue a new dev for pendulum. Closing
