### ISSUE TITLE
Test Java version of MOTHA for bugs

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#656]
Since @pixelzoom will soon be resuming his port of Models of the Hydrogen Atom (MOTHA) the legacy sim should be tested for any bugs. It is quite a complex sim, although no current unfuddle issues exist.

As usual, please report any issues in the repo and mark them as a "legacy bug"

**Comment by pixelzoom** [comment]
When porting a Java sim, it's also typically a good idea to triage any issues that are in Unfuddle. In the case of this sim, there is only one such issue (https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/547, larger play area on Mac causes layout problems) which is irrelevant for HTML5 sims.

**Comment by pixelzoom** [comment]
> although no current unfuddle issues exist.

When porting a Java sim, it's typically a good idea to triage any issues that are in Unfuddle. In the case of this sim, there is in fact one such issue ([Unfuddle#547](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/547), larger play area on Mac causes layout problems), but that issue is irrelevant for HTML5 sims.

**Comment by phet-steele** [comment]
@ariel-phet @pixelzoom Java version tested, it's relatively solid.
