### ISSUE TITLE
Modmic - new headphones

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/tasks#660]
To use the Modmic for future recordings, Stephanie suggested the following:

Get a new magnetic clip for the modmic, and a smaller, lightweight headphone set that it can be attached to.  The old headphones are too large and loose, with lots of pieces to rub on one another, and so is creating rubbing noise as the person wearing the headphones moves or speaks.  The magnetic clip seems to be permanently attached to those headphones so we need a new magnetic clip.  Also, the old headphones can be added to the asset inventory as separate headphones.

@arnabp   Can we briefly discuss this when you are back with PhET in the fall?

**Comment by arnabp** [comment]
What price range are you looking at for this?

**Comment by amyh-phet** [comment]
@arnabp   I think less than $100 if we can find something.  I'll check with others who are recording primers to see if they are actively using the modmic as I think we've gone to using the separate mic you ordered last fall.

**Comment by amyh-phet** [comment]
@arnabp    It sounds like this would be helpful to have.  Can you price out options please?

**Comment by arnabp** [comment]
[Senheiser HD 419](https://www.amazon.com/Sennheiser-HD-419-Headphones-Black/dp/B005N8W1MO) ($49.99) and  [Senhesier HD 429](https://www.amazon.com/Sennheiser-HD-429-Headphones-Black/dp/B005N8W1Q0/) ($37.99) are both great options (some slight differences between them).

You did, however, say "small" so I'm not sure what that constitutes, since these are both over ear designs. If you'd prefer a smaller on ear design then the [ATH-SJ11](https://www.amazon.com/Audio-Technica-ATH-SJ11-Headphones-Black/dp/B004KCJJ4M/) ($30.42) or [Senhesier PX 100](https://www.amazon.com/Sennheiser-100-II-Ear-Miniheadphone-Black/dp/B002VPDOH8/) ($46.14) might be better.

**Comment by amyh-phet** [comment]
@arnapb   I think we are going to try and see if we can pass around the larger mic on a stand you set up for us in January.  I think Stephanie is done recording primers, so we likely won't order this for a while.  I'll make a note of what you found, then close the issue.  Thanks for tracking this down in case we need to order.
