### ISSUE TITLE
dev test State of Matter 1.0.0-dev.11

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#694]
A new dev version has been created for SOM since we got word that some folks outside of PhET are putting together some learning materials using the old Java version, and we thought they might want to work with the soon-to-be-published HTML5 version instead.  We are providing them the link to this dev version.

As of this writing, the task to test the previous dev version (v1.0.0-dev.10) is still open, so I will close it and further dev testing should be done on this new version.

Here is a link:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.11/states-of-matter_en.html

Platforms:

- [x] iPad2
- [x] Mac Safari
- [x] Win Chrome

**Comment by ariel-phet** [comment]
Bumping to medium for the moment, as plinko is closer to publication

**Comment by phet-steele** [comment]
@ariel-phet, I spoke with @jbphet and this is what we decided. The QA team has only scratched the surface on this dev version. There have been **radical** changes to the sim's code since this task opened. Any additional time spent on this dev version would be time wasted. Closing this task for the new release coming up shortly.
