### ISSUE TITLE
migrate Google docs owned by jbphet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#740]
@jbphet You currently own “PhET Versioning for HTML5 Development”. You’ll need to fix the ownership and migrate it. Coordinate with @oliver-phet or @amanda-phet. The link is https://docs.google.com/document/d/1N_kMz46EZqQqixiwoOczB8gAW9pvRHyx5iHEzhXu0os/edit.

**Comment by pixelzoom** [comment]
Ditto for these docs:

HTML5 Development Process
https://docs.google.com/document/d/1lK1OBbwC7O3oidY9RN4-MTZ1uJWiS3DJ5tAuB_bJaUI/edit?usp=drive_web

HTML5 Meeting Notes 10/12/2012
https://docs.google.com/document/d/1xUamZ-DxAvpcLPLa8jtvGcQ8xQeytp_pAalqodbf6lE/edit?usp=drive_web

**Comment by pixelzoom** [comment]
PhET’s HTML5 Development Process for Contractors
https://docs.google.com/document/d/1_1WAZMfPthjSoT8HvTdAgt4szCe6axIkqrfSdYrSivY/edit

**Comment by pixelzoom** [comment]
Tablet Sim Development: Contacts and Potential Collaborators
https://docs.google.com/document/d/1OiCk3n38DeZ5lOKiIqPzMGnVXLfCwlrlY2XjbyJRfQQ/edit

**Comment by pixelzoom** [comment]
PHET-iO meeting 2016
https://docs.google.com/document/d/1LeDVWnhAZ06Dj818ttin3X0JAGY37OyHUJ2d6l9XMxw/edit

**Comment by pixelzoom** [comment]
I'm not going to add more docs here. @jbphet Recommended that you look at what Google docs you own, determine which are personal vs PhET, and migrate the PhET ones.

**Comment by ariel-phet** [comment]
assigning myself...I might be able to move some of these

**Comment by jbphet** [comment]
There was an issue way back when I was first using my colorado.edu account where I was unable to transfer doc ownership to a different domain, such as phethelp@gmail.com.  I worked with @ariel-phet to try to figure this out, but we never came up with a way to make it work, and just left them in place (except for a few that were vital, which were copied).  @ariel-phet - I'm going to leave this in your hands for now since you said that you'd take a look.  Please let me know if you need me to take any action.

**Comment by oliver-phet** [comment]
I just talked with @jbphet about this and this issue can be closed since all of the docs in question are on the @colorado.edu domain. They will not be organized in the 'phet files' folder structure, but can be in the future.
