### ISSUE TITLE
Test Progress Indicators on supported platfoms

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#744]
Today @ariel-phet and I met to polish the progress indicators as part of https://github.com/phetsims/joist/issues/348, and we prepared two examples for dev testing:

**A sim with several screens:**
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.2.4-dev.1/energy-skate-park-basics_en.html

**A sim with one screen:**
http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.3.7-dev.1/faradays-law_en.html

Please test these on:

- [x] Windows + Chrome/Firefox/Edge/IE11
- [x] Mac + Chrome/Firefox/Safari
- [x] iPad + Mobile Safari (iOS 9)
- [x] iPad + Mobile Safari (iOS 10)

Reassigned to @ariel-phet to review this request, make any desired changes, prioritize and reassign.

**Comment by samreid** [comment]
When this issue is complete, please reassign https://github.com/phetsims/tasks/issues/744 to me for next steps.

**Comment by ariel-phet** [comment]
I checked on all browsers for Win7 and Win10, all looks very good.

Also checked iPad2 iOS 9.3.5, looked good.

@phet-steele these tests only take a few moments, and it would be nice if we were able to have this upgrade available in master so our next published sim (probably SOM) includes this change.

Please test iOS 10 and the Mac browsers.

Marking as high priority mainly since these tests will likely take less than a few minutes.

**Comment by phet-steele** [comment]
Looked good. Couldn't really think of any tests that could break it. I tried to see if the sim loaded properly when it was in the background, and made sure slow internet still looked fine. The little bar chugged along each time.

**Comment by samreid** [comment]
Thanks @phet-steele, closing.
