### ISSUE TITLE
Test commas in query parameters

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#771]
Before we proceed with rolling out a huge number of maintenance releases for https://github.com/phetsims/joist/issues/399 we would like to check whether commas are supported as query parameters on **all of our platforms**.

To test this, you can launch:
https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_en.html?screens=2,3

and check whether it is only showing the "Phase Changes" and "Interaction" screens and make sure it is not crashed.  It may be beneficial to have the console open (where possible) in case trouble is reported there.

Assigned to @ariel-phet for prioritization, scheduling and delegation.  Also, please add any appropriate labels.

- [x]  macOS 10.12 browsers
- [x] Mac OSX 10.11 browsers
- [x] Mac OSX 10.10 browsers
- [x] Mac OSX 10.9 browsers
- [x] Win 10 browsers
- [x] Win 8.1 browsers
- [x] Win 7 browsers
- [x] iOS 9.3.5
- [x] iOS 10
- [x] Chromebook

**Comment by ariel-phet** [comment]
@phet-steele, this is low priority, however, since you have some RC testing to do coming up, perhaps this test could be performed on each platform concurrent with an RC test? Basically it is just "open the link, and make sure it is running with only those two screens". Might be easy to couple with the MAT test.

**Comment by phet-steele** [comment]
@samreid every platform/browser loaded properly.
