### ISSUE TITLE
Vimeo PhET Amara translations (primers)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#896]
@arouinfar Do you happen to know how we are supporting translation of our Vimeo video subtitles (primers)?

It looks like Vimeo no longer integrates with Amara: https://help.vimeo.com/hc/en-us/articles/224968828-Captions-and-subtitles?flash_digest=5b8d6d78e5394081575fe70dd56d6ea78d29172b

And you have to manually upload translations for each video.

**Comment by amanda-phet** [comment]
I have never seen a translated video, but @CWilson4960 recently added subtitles to a primer. I believe she had to manually upload the script and do the captioning, but I'm not aware of how these get translated.

**Comment by CWilson4960** [comment]
Last week, I uploaded and captioned a Vimeo video using Amara without any trouble, so I'm not sure the extent to which Vimeo is no longer integrating with Amara. The Least Squares Regression primer on the PhET website has Amara subtitles (I'm working on adding them to the intro and outro, but right now they're just in the body). So Amara subtitles are still working on Vimeo videos. 
From what I can see of the phet_amara account, under the messages tab, people submit their own translated captions, and the phet account updates the video.

**Comment by arouinfar** [comment]
@oliver-phet I believe we have been using Amara because of its translation support (primarily for our YouTube videos). As far as I know, we have always logged into Amara to create the subtitles and then uploaded the subtitle file to Vimeo, as @CWilson4960 has said.

I am not aware of translated primers, and I'm not sure if there's a demand for them. Looking at the Amara account settings, it seems like an email notification should be sent to phethelp when there are new translations, but I'm not sure how a translator would find our videos on Amara. Our YouTube account is synced with Amara, and I believe that the translators can submit captions directly through YouTube.

I dug a little into the Vimeo stats, and it looks like there are at least some international views, but perhaps that would be larger if the videos had translated captions. Here's a breakdown of the primer views since January 1, 2015 (the furthest back that Vimeo stats will go) for the top 10 countries.
<img width="639" alt="screen shot 2017-10-02 at 2 04 18 pm" src="https://user-images.githubusercontent.com/8419308/31096885-a917521e-a77a-11e7-8d74-4a1f006d8689.png">

**Comment by oliver-phet** [comment]
That's what I thought. @ariel-phet do you want to support translation of our primers? It would likely require us making the current captions available to translators, accepting translations of the captions, then uploading them to vimeo.

**Comment by ariel-phet** [comment]
@oliver-phet @amanda-phet the Japanese visitors were specifically interested in the possibility of subtitling. 

@amanda-phet perhaps when you meet with them tomorrow, let them know to email Oliver in the future if they are interested in translating the subtitles of the primers since it sounds like we could support that effort.

**Comment by ariel-phet** [comment]
@oliver-phet this might also come up with our visit to Mexico, I could see Spanish subtitles being popular as well.

**Comment by amanda-phet** [comment]
@ariel-phet I forgot to specifically mention primers to the Japanese visitors, sorry. Hiroto translated Area Builder, so I did tell him to translate some more sims! :) 

What else needs to be done with this issue?

**Comment by ariel-phet** [comment]
@oliver-phet was going to bring this up at next status meeting. Seems there are some aspects that would be good to discuss with @kathy-phet

**Comment by oliver-phet** [comment]
It sounds like we are going to proceed with moving to Youtube. Closing for now.
