### ISSUE TITLE
Create ability to remotely "pull all" repositories on Phettest

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#9]
Hey @orejolaphet, we discussed a long time to have the ability to remotely "pull all" repositories on phettest.This is a "wishlist item" but in case you have some downtime at some point we should look into it again.

**Comment by ariel-phet** [comment]
Hey @BrianNewsom -- this might be an interesting little project that you would have the skill set to help out with. I will email with some more details.

**Comment by samreid** [comment]
I'd also recommend running `clone-missing-repos.sh` before or after the mass pull, in case any new repos have been created.

**Comment by ariel-phet** [comment]
@samreid is it possible to make sure no private repos are included in this missing repos script for the moment? Private repos require a password each time which currently stalls the pull-all script unless someone is there to manually enter the password for each one, so we have taken all private repos off phettest (since they are not necessary for testing purposes at the moment)

**Comment by samreid** [comment]
I compared the list of active-repos used by clone-missing-repos (which is https://github.com/phetsims/chipper/blob/master/data/active-repos ) against our list of private repos which you can view here https://github.com/phetsims/?query=+only%3Aprivate+ and didn't see any matches.  Do you know what repos this has been a problem for in the past, and do you know if this is still a problem at the moment?

**Comment by ariel-phet** [comment]
Oh, I have never used the clone-missing-repos script...I just assumed it would also grab the private ones as well. If it is only grabbing the repos with dependencies that is great.

**Comment by samreid** [comment]
Well, I haven't tried any scripts from a non-admin account, so just let me know what problems you run into.

**Comment by BrianNewsom** [comment]
@ariel-phet I will get to this once I'm back on campus! I am home for break and cannot access the machine, but I have an implementation plan and it shouldn't be too bad.

**Comment by ariel-phet** [comment]
Sounds good @BrianNewsom!

**Comment by ariel-phet** [comment]
Bumping up the priority of this issue, since it is becoming more important.

@BrianNewsom - do you have an update on how this work is going?

**Comment by BrianNewsom** [comment]
Hey Ariel,

Thanks for letting me know the priority is bumped - I will prioritize it more, I was just working on a few other things since I was a little stuck.  Things are going fairly well. I've set up a node backend to run the script and its "working" with my supervision.  I'm stuck on two things right now
* Apache times out my requests because the script takes too long to run.  I've tried setting a higher time but I can't find the correct flag for what I need in the config file. The script continues to execute but it takes you to an ugly page so I'd like to fix that.
* When I run the backend through git bash it works fine, but I've set it up as a service using nssm.  For some reason in the latter case the script doesn't get run.  It doesn't fail, but it never executes.  I'm troubleshooting this right now.

Once I can overcome these issues it should be good to go. I think the second one shouldn't be too hard, but I don't have a plan for the first.

**Comment by BrianNewsom** [comment]
@ariel-phet I believe I am mostly done here.  The script takes forever to run, but there's not really anything to be done.  If it fails, it should redirect and tell the person on the page that it has failed, otherwise it will redirect and give a success message.

Ended up being basically just a php script that runs on the backend.  Sorry I got caught up in node - seemed like a good idea at the time.

Let me know if you have any issues or if you'd like to see anything changed.

Brian

**Comment by ariel-phet** [comment]
@BrianNewsom - excellent, I will check it out!

Were you also able to set up some sort of "chronjob" to run this script?

**Comment by ariel-phet** [comment]
Worked for me (even from a VPN connection).

I think having this script automatically run once a day at say 1:00 am or so would be a great final step

**Comment by BrianNewsom** [comment]
@ariel-phet I've set up the task - however to run it when the user is not logged in I need to create a password for the user on the computer.  Is it okay if I set this up?

**Comment by ariel-phet** [comment]
Yes, I will email you the password

**Comment by BrianNewsom** [comment]
Thanks @ariel-phet.. I believe I have it configured.  I will verify that it worked tomorrow morning then it should be set!

**Comment by oliver-phet** [comment]
@BrianNewsom Would it be easy to add a screen to the PhET test page to show the date it was last updated...
![screen shot 2015-04-29 at 2 12 38 pm](https://cloud.githubusercontent.com/assets/5090275/7400495/8f333658-ee7a-11e4-9c2f-d8325efd44ae.jpg)

**Comment by BrianNewsom** [comment]
Yeah, absolutely. I'll try and get that implemented!

Thanks for the idea!

**Comment by jonathanolson** [comment]
While in the office, I wrote a Node.js script (which can launch git nicely) that will go through active repos and clone/pull as necessary: htdocs/refresh-server.js.

It's running right now in git-bash, and the "Refresh All Sims" button works (confirmed to pull a token commit).

**Comment by ariel-phet** [comment]
Since this all seems to be working, closing. Will eventually make phettest a linux box.
