### ISSUE TITLE
Copyright date in iframe source code

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/tasks#902]
I noticed that the copyright date in the iframe source code is

`
`

Does this need to be changed?

**Comment by phet-steele** [comment]
Specifically in the test link we use on spot: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.2/capacitor-lab-basics_en-iframe.html

**Comment by ariel-phet** [comment]
@samreid I believe we have some automated code in other places that keeps this up to date. Is this something that could easily be fixed up?

Nice catch @lmulhall-phet!

**Comment by samreid** [comment]
In https://github.com/phetsims/chipper/commit/18cc4eca7e859000e4717ca4e821f90042701d7a I updated the copyright date in the iframe template HTML to 2002-2017 (though I noticed the last commit before this was from 2016).

The automated tool to update copyrights only works on JS code.  When I tried running it across our active-runnables like so:

```
for-each.sh active-runnables grunt update-copyright-dates
```

I observed that it updated 372 files.  @ariel-phet would you like me to spot check and commit these updates?  Should I run this on `active-repos` which adds another 40 repos?  I'm not familiar with all of them so that may take more time to make sure the changes are compatible.

**Comment by ariel-phet** [comment]
@samreid spot check and commit sounds good. I don't think you need to do this on active-repos at the moment.

**Comment by samreid** [comment]
I spot checked 10 files or so and all changes match expectations.  I also noticed changes in the *.config files, which were recently automatically generated.  Still, it doesn't seem to do any harm to update them in this commit (even if the copyright date gets overwritten with 2017 next time they auto-update).

**Comment by samreid** [comment]
372 files originally marked as changed, then I decided to run `for-each.sh active-runnables grunt generate-config` and now we are down to 295, so I'll go with that.

**Comment by samreid** [comment]
Committed and closing.

**Comment by phet-steele** [comment]
@samreid who needs spot checks when you have Bayes! It revealed three issues:

```

/data/share/phet/continuous-testing/snapshot-1510331419792/curve-fitting/js/curve-fitting/view/CurveNode.js
  1:1  error  Incorrect copyright statement in first comment  copyright

/data/share/phet/continuous-testing/snapshot-1510331419792/plinko-probability/js/common/view/BallsNode.js
  1:1  error  Incorrect copyright statement in first comment  copyright

/data/share/phet/continuous-testing/snapshot-1510331419792/plinko-probability/js/common/view/PegsNode.js
  1:1  error  Incorrect copyright statement in first comment  copyright
```

**Comment by samreid** [comment]
Thanks @phet-steele and `@bayes`!  Some of those `Copyright -2017` dates indicate code over 4000 years old!  Commit on the way.

**Comment by samreid** [comment]
The commits are here, I'll check bayes again in an hour or so to see how we are doing.

**Comment by samreid** [comment]
Bayes seems ok, closing for now.
