### ISSUE TITLE
Design Thinking process graphic

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#990]
From conversation with @elharden2 today: 

Learn _(about the users and context)_
Define _(the problem or design challenge)_
**Brainstorm** _(design ideas)_
**Build and Refine** _(a prototype)_
**Test and Retest** _(the prototype)_
Share

Brainstorm, Build and Refine, and Share steps can be displayed in a circle (like the 'Research' step in the PhET R&D diagram) to indicate that you can cycle through these steps as many times as needed until you feel like you have a final product or design

_Originally posted by @emily-phet in https://github.com/phetsims/a11y-research/issues/131#issuecomment-466530862_

**Comment by emily-phet** [comment]
Sorry for the confusing issue - using commenting across repos for the first time. 

Here's the original comment https://github.com/phetsims/a11y-research/issues/131#issue-410031492 that was discussed in the a11y repo. The final wording was decided on and that is what is commented above. 

Would like to have a finalized version of this by mid-March.

**Comment by ariel-phet** [comment]
@kellywurtz is on the case

**Comment by ariel-phet** [comment]
@kellywurtz questions can be directed to @elharden2

**Comment by kellywurtz** [comment]
@emily-phet @elharden2 Re-posting since I accidentally posted in the old issue. Here's the first draft! (things inside the learn circle are a bit off-center in this version, will be fixed in the next draft). 

![image](https://user-images.githubusercontent.com/42352972/53439170-b41ed600-39be-11e9-8d98-8ba205f708f9.png)

**Comment by emily-phet** [comment]
@kellywurtz very nice! I really like the color palette and the little icons. A few thoughts:
- How about a color a little more green for "test"
- can you move the whole "brainstorm, build+refine, test" circle up, so that the center of the 'circle' is even with the 'learn, define, share' row?
@elharden2 Any other suggestions?

**Comment by elharden2** [comment]
@kellywurtz @emily-phet Agreed! The colors are great and it's a fun little graphic.  I concur on shifting the cyclical process up so that it is more in line with the rest of the process.  One thought I have is looking at it now, it seems like having 'Build and Refine' in the same circle is a bit confusing. Wouldn't the sequence more likely be Build-->Test-->Refine OR Build-->Test-->Brainstorm-->Refine?  It doesn't really make sense to build a design and immediately refine it in the same step, which is probably how kids would interpret this in its current form.  I think either we should drop the Refine, or maybe change the '+' in Build + Refine to an 'or', so Build or Refine. What do you think?

**Comment by kellywurtz** [comment]
@elharden2 I'd say I'm in favor of making it an "or" instead of dropping "refine" entirely. I'll wait to hear @emily-phet 's opinion on that ordering/wording, but for now, here's a new version with the cyclic process up higher.

<img width="939" alt="screen shot 2019-03-07 at 8 09 14 am" src="https://user-images.githubusercontent.com/42352972/53966452-6ede6080-40b0-11e9-8171-7b83e926993c.png">

**Comment by emily-phet** [comment]
Whatever @elharden2 thinks will be the most helpful for the students she works with. We can always tweak more later after seeing how they interpret it. 

Also, maybe we could try not having the light grey color (which somehow looks more egg shaped than circular - though I think it's a circle). Maybe having the arrows going around the circle look different than the ones going left to right - perhaps that would help the circular area stand out as distinct?

**Comment by elharden2** [comment]
Let's change the + to an 'or' so it says 'Build or Refine'. And I agree, let's nix the light gray background circle and just keep it simple.  Looks great, @kellywurtz, thanks!!

**Comment by kellywurtz** [comment]
@elharden2 @emily-phet Here's a version without the grey background. As far as using different arrows goes, these are ever so slightly different, but another idea is using outlines of arrows (white center) instead of the solid ones I have right now. That option not built into Illustrator, so since it would take a few extra steps, I figured I would see how you guys feel about the idea first, or if you're happy with this design.

![designthinkinggraphic_draft3](https://user-images.githubusercontent.com/42352972/54322487-f77e6480-45ba-11e9-8366-3d60d2aa12cf.png)

Alternatively, here's a version with white arrows, which I think looks better than the last one with a grey background. 

![designthinkinggraphic_draft4](https://user-images.githubusercontent.com/42352972/54322676-b9ce0b80-45bb-11e9-8708-645d50b60738.png)

**Comment by emily-phet** [comment]
Syncronicity! I was thinking of suggesting an 'inverted' style arrow for the circular portion. 
I like the upper version, with now grey background circle. This one may be fine as is - @elharden2 do you think the upper version would work for a first go?

**Comment by kellywurtz** [comment]
@emily-phet Can you explain "inverted" further?

**Comment by elharden2** [comment]
@emily-phet Just to clarify, you like the version with the light gray circle and white arrows for the cyclical portion?  I am fine with either one, and yes I think we have what we need for a first go.  Thanks @kellywurtz!

**Comment by ariel-phet** [comment]
This issue appears stale. Closing
